// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_lV57TtO_iolj3iCBZVlf28chUtk6ksQ',
    appId: '1:115397993317:web:0d6e6fdf5dca55e572778c',
    messagingSenderId: '115397993317',
    projectId: 'medi-remind-app',
    authDomain: 'medi-remind-app.firebaseapp.com',
    databaseURL: 'https://medi-remind-app-default-rtdb.firebaseio.com',
    storageBucket: 'medi-remind-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA37eSTPfeZ4Xrr-MJOKpDDfBS_Y7u99hg',
    appId: '1:115397993317:android:d2c0baae8682fac172778c',
    messagingSenderId: '115397993317',
    projectId: 'medi-remind-app',
    databaseURL: 'https://medi-remind-app-default-rtdb.firebaseio.com',
    storageBucket: 'medi-remind-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDriWbwv4O5UF74vEgiLD1p8bJnkx0V_pA',
    appId: '1:115397993317:ios:e6ce408f048c14c872778c',
    messagingSenderId: '115397993317',
    projectId: 'medi-remind-app',
    databaseURL: 'https://medi-remind-app-default-rtdb.firebaseio.com',
    storageBucket: 'medi-remind-app.firebasestorage.app',
    iosBundleId: 'com.example.mediremindapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDriWbwv4O5UF74vEgiLD1p8bJnkx0V_pA',
    appId: '1:115397993317:ios:e6ce408f048c14c872778c',
    messagingSenderId: '115397993317',
    projectId: 'medi-remind-app',
    databaseURL: 'https://medi-remind-app-default-rtdb.firebaseio.com',
    storageBucket: 'medi-remind-app.firebasestorage.app',
    iosBundleId: 'com.example.mediremindapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_lV57TtO_iolj3iCBZVlf28chUtk6ksQ',
    appId: '1:115397993317:web:8ea8316ef413bb7172778c',
    messagingSenderId: '115397993317',
    projectId: 'medi-remind-app',
    authDomain: 'medi-remind-app.firebaseapp.com',
    databaseURL: 'https://medi-remind-app-default-rtdb.firebaseio.com',
    storageBucket: 'medi-remind-app.firebasestorage.app',
  );

}