// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX33GYYLF0J3dQX7zVvdUoOF56fcbZZUY',
    appId: '1:572180350092:web:ba73e19cce832a1b8ae7a9',
    messagingSenderId: '572180350092',
    projectId: 'tinderjob-e9eeb',
    authDomain: 'tinderjob-e9eeb.firebaseapp.com',
    storageBucket: 'tinderjob-e9eeb.firebasestorage.app',
    measurementId: 'G-EZ25685S6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl97NrhK2G51psOIK-8PSuWjbq5xUkxzk',
    appId: '1:572180350092:android:b7dcb80a994114f28ae7a9',
    messagingSenderId: '572180350092',
    projectId: 'tinderjob-e9eeb',
    storageBucket: 'tinderjob-e9eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQrygULhtWMKgzzME208ZMzojjYf3Dy0',
    appId: '1:572180350092:ios:68f77b7e7928fb758ae7a9',
    messagingSenderId: '572180350092',
    projectId: 'tinderjob-e9eeb',
    storageBucket: 'tinderjob-e9eeb.firebasestorage.app',
    iosBundleId: 'com.example.tinderjob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoQrygULhtWMKgzzME208ZMzojjYf3Dy0',
    appId: '1:572180350092:ios:68f77b7e7928fb758ae7a9',
    messagingSenderId: '572180350092',
    projectId: 'tinderjob-e9eeb',
    storageBucket: 'tinderjob-e9eeb.firebasestorage.app',
    iosBundleId: 'com.example.tinderjob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX33GYYLF0J3dQX7zVvdUoOF56fcbZZUY',
    appId: '1:572180350092:web:045487b6d3c17f9a8ae7a9',
    messagingSenderId: '572180350092',
    projectId: 'tinderjob-e9eeb',
    authDomain: 'tinderjob-e9eeb.firebaseapp.com',
    storageBucket: 'tinderjob-e9eeb.firebasestorage.app',
    measurementId: 'G-5BRJVM906M',
  );
}
