name: mobile_app_exam
description: AniMarket – Local Animal Buy & Sell Platform
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  provider: any
  firebase_auth: ^5.6.2
  google_sign_in: ^6.1.6
  url_launcher: ^6.1.7
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.2.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/paypal_checkout.html
    - assets/my_logo.png
