// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhkUgGc8tm8UEVjh61IbQhD4Y88xmCz2I',
    appId: '1:838101042348:web:8660e712d3798a6a4d0b09',
    messagingSenderId: '838101042348',
    projectId: 'umusare-1c1be',
    authDomain: 'umusare-1c1be.firebaseapp.com',
    storageBucket: 'umusare-1c1be.firebasestorage.app',
    measurementId: 'G-H4FRG96BX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDujad5KVMoZPvVyhf1IYyTCtuhQhdVO3w',
    appId: '1:838101042348:android:3e602b509f91e3ad4d0b09',
    messagingSenderId: '838101042348',
    projectId: 'umusare-1c1be',
    storageBucket: 'umusare-1c1be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEYv8Bc1f5zKDuvlqo_dMjv6fS99Q_L2M',
    appId: '1:838101042348:ios:4faf32e2ee3817154d0b09',
    messagingSenderId: '838101042348',
    projectId: 'umusare-1c1be',
    storageBucket: 'umusare-1c1be.firebasestorage.app',
    iosBundleId: 'com.example.umusare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEYv8Bc1f5zKDuvlqo_dMjv6fS99Q_L2M',
    appId: '1:838101042348:ios:4faf32e2ee3817154d0b09',
    messagingSenderId: '838101042348',
    projectId: 'umusare-1c1be',
    storageBucket: 'umusare-1c1be.firebasestorage.app',
    iosBundleId: 'com.example.umusare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhkUgGc8tm8UEVjh61IbQhD4Y88xmCz2I',
    appId: '1:838101042348:web:e47d2cddd70141d64d0b09',
    messagingSenderId: '838101042348',
    projectId: 'umusare-1c1be',
    authDomain: 'umusare-1c1be.firebaseapp.com',
    storageBucket: 'umusare-1c1be.firebasestorage.app',
    measurementId: 'G-330X4XEVK2',
  );
}
