// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCFXRtIPP3vdcb9GVSISJTGn7pL-rHUeo',
    appId: '1:349692478394:web:c2488e0df297d79b275383',
    messagingSenderId: '349692478394',
    projectId: 'smartdaily-57cbe',
    authDomain: 'smartdaily-57cbe.firebaseapp.com',
    storageBucket: 'smartdaily-57cbe.firebasestorage.app',
    measurementId: 'G-DLPY0J6RJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcgKrL4QPpHPcwryBkOJnwIlmB-OauHnw',
    appId: '1:349692478394:android:1dcc12bcdf8c7dcc275383',
    messagingSenderId: '349692478394',
    projectId: 'smartdaily-57cbe',
    storageBucket: 'smartdaily-57cbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC91dVmKkmqTIfSngn-0-ykWBF7rpBFZ2o',
    appId: '1:349692478394:ios:df1a8fab1b359a50275383',
    messagingSenderId: '349692478394',
    projectId: 'smartdaily-57cbe',
    storageBucket: 'smartdaily-57cbe.firebasestorage.app',
    iosBundleId: 'com.example.smartDaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC91dVmKkmqTIfSngn-0-ykWBF7rpBFZ2o',
    appId: '1:349692478394:ios:df1a8fab1b359a50275383',
    messagingSenderId: '349692478394',
    projectId: 'smartdaily-57cbe',
    storageBucket: 'smartdaily-57cbe.firebasestorage.app',
    iosBundleId: 'com.example.smartDaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCFXRtIPP3vdcb9GVSISJTGn7pL-rHUeo',
    appId: '1:349692478394:web:541f0b9db193874c275383',
    messagingSenderId: '349692478394',
    projectId: 'smartdaily-57cbe',
    authDomain: 'smartdaily-57cbe.firebaseapp.com',
    storageBucket: 'smartdaily-57cbe.firebasestorage.app',
    measurementId: 'G-RWGNQYGTK9',
  );
}
