// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqPE9JiFrJGJvJtIHkNhd14_mI3bBRXk',
    appId: '1:256018141908:web:cc33ed31c006fac35be141',
    messagingSenderId: '256018141908',
    projectId: 'bmirecords-acb0b',
    authDomain: 'bmirecords-acb0b.firebaseapp.com',
    storageBucket: 'bmirecords-acb0b.firebasestorage.app',
    measurementId: 'G-F1WLMTNF57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEY0V9dqITzVH5LM6lN2RaOEmSx4tgcyg',
    appId: '1:256018141908:android:2e5e0b83fdc746f35be141',
    messagingSenderId: '256018141908',
    projectId: 'bmirecords-acb0b',
    storageBucket: 'bmirecords-acb0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5LOnQDxRz0hbm1gJtJHqfTmadIuMMG_o',
    appId: '1:256018141908:ios:09fa9e443b04afea5be141',
    messagingSenderId: '256018141908',
    projectId: 'bmirecords-acb0b',
    storageBucket: 'bmirecords-acb0b.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5LOnQDxRz0hbm1gJtJHqfTmadIuMMG_o',
    appId: '1:256018141908:ios:09fa9e443b04afea5be141',
    messagingSenderId: '256018141908',
    projectId: 'bmirecords-acb0b',
    storageBucket: 'bmirecords-acb0b.firebasestorage.app',
    iosBundleId: 'com.example.calculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvqPE9JiFrJGJvJtIHkNhd14_mI3bBRXk',
    appId: '1:256018141908:web:4199940a76c75cb55be141',
    messagingSenderId: '256018141908',
    projectId: 'bmirecords-acb0b',
    authDomain: 'bmirecords-acb0b.firebaseapp.com',
    storageBucket: 'bmirecords-acb0b.firebasestorage.app',
    measurementId: 'G-XDDY9MDBN6',
  );
}
