// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdKrXAKxudt4XkKkHUwu2E3lQp0hUyrzA',
    appId: '1:1065973699783:android:398a5c233f0914ff049ae2',
    messagingSenderId: '1065973699783',
    projectId: 'mystudysync',
    storageBucket: 'mystudysync.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMezh52efkYdbCHSK-uhzFlLMnRpd05nw',
    appId: '1:1065973699783:web:04853048d2596998049ae2',
    messagingSenderId: '1065973699783',
    projectId: 'mystudysync',
    authDomain: 'mystudysync.firebaseapp.com',
    storageBucket: 'mystudysync.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMezh52efkYdbCHSK-uhzFlLMnRpd05nw',
    appId: '1:1065973699783:web:04853048d2596998049ae2',
    messagingSenderId: '1065973699783',
    projectId: 'mystudysync',
    authDomain: 'mystudysync.firebaseapp.com',
    storageBucket: 'mystudysync.firebasestorage.app',
    measurementId: 'YOUR_MEASUREMENT_ID', // Optional, add if you have it
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
