// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvEz9J4RidSHGIsFjz7afhVRcRG1aZwU',
    appId: '1:639979092765:web:3b65fcea0e6a00a1fcbff4',
    messagingSenderId: '639979092765',
    projectId: 'phonestore-1e589',
    authDomain: 'phonestore-1e589.firebaseapp.com',
    storageBucket: 'phonestore-1e589.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1BBaQDlE4rvMQDuzj6J7tZvYh0ng2SM',
    appId: '1:639979092765:android:498b4d3a863ec756fcbff4',
    messagingSenderId: '639979092765',
    projectId: 'phonestore-1e589',
    storageBucket: 'phonestore-1e589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAir7uBBtXEAlWt-X1Ib4yDbLpCr5OEGiM',
    appId: '1:639979092765:ios:7bbbbadc7b5ce8a6fcbff4',
    messagingSenderId: '639979092765',
    projectId: 'phonestore-1e589',
    storageBucket: 'phonestore-1e589.firebasestorage.app',
    iosClientId: '639979092765-fvv9s6chchkfo044ejk6rlpluidb74du.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAir7uBBtXEAlWt-X1Ib4yDbLpCr5OEGiM',
    appId: '1:639979092765:ios:7bbbbadc7b5ce8a6fcbff4',
    messagingSenderId: '639979092765',
    projectId: 'phonestore-1e589',
    storageBucket: 'phonestore-1e589.firebasestorage.app',
    iosClientId: '639979092765-fvv9s6chchkfo044ejk6rlpluidb74du.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuvEz9J4RidSHGIsFjz7afhVRcRG1aZwU',
    appId: '1:639979092765:web:122f64fdb0265c27fcbff4',
    messagingSenderId: '639979092765',
    projectId: 'phonestore-1e589',
    authDomain: 'phonestore-1e589.firebaseapp.com',
    storageBucket: 'phonestore-1e589.firebasestorage.app',
  );

}