// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1ic1oYZSewTqnmIYU5L2c4HDle0yG1s',
    appId: '1:966900733600:web:46c177083b9fb1a810dbc5',
    messagingSenderId: '966900733600',
    projectId: 'faith-2025',
    authDomain: 'faith-2025.firebaseapp.com',
    storageBucket: 'faith-2025.firebasestorage.app',
    measurementId: 'G-DLZWRK76YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj1KILU-2oKxI1vYcJnk2HNGUrYPcLYxw',
    appId: '1:966900733600:android:621d65685f43c94a10dbc5',
    messagingSenderId: '966900733600',
    projectId: 'faith-2025',
    storageBucket: 'faith-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKckhOkz5b-1NymcnXDQ6zMM7UtggR-dU',
    appId: '1:966900733600:ios:d06c166b9f7ccf0e10dbc5',
    messagingSenderId: '966900733600',
    projectId: 'faith-2025',
    storageBucket: 'faith-2025.firebasestorage.app',
    iosClientId: '966900733600-hgu6ovk50t9ie9lvk8gjb1k4dor65sjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.faith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKckhOkz5b-1NymcnXDQ6zMM7UtggR-dU',
    appId: '1:966900733600:ios:d06c166b9f7ccf0e10dbc5',
    messagingSenderId: '966900733600',
    projectId: 'faith-2025',
    storageBucket: 'faith-2025.firebasestorage.app',
    iosClientId: '966900733600-hgu6ovk50t9ie9lvk8gjb1k4dor65sjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.faith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf1ic1oYZSewTqnmIYU5L2c4HDle0yG1s',
    appId: '1:966900733600:web:f5c8b8168120e92c10dbc5',
    messagingSenderId: '966900733600',
    projectId: 'faith-2025',
    authDomain: 'faith-2025.firebaseapp.com',
    storageBucket: 'faith-2025.firebasestorage.app',
    measurementId: 'G-9PDC4QHZYR',
  );

}