// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDELO4_6o0WQ2VGJBO1YO0sLgSYy0jfNWI',
    appId: '1:192956021233:web:e99be58937eca50212ac50',
    messagingSenderId: '192956021233',
    projectId: 'easyrent2-3a17f',
    authDomain: 'easyrent2-3a17f.firebaseapp.com',
    storageBucket: 'easyrent2-3a17f.firebasestorage.app',
    measurementId: 'G-ZWY1G60N8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE19yjGMSaHYWphLasi-kEWgTMfb_1k0I',
    appId: '1:192956021233:android:ac40ddc1a6fe5b2f12ac50',
    messagingSenderId: '192956021233',
    projectId: 'easyrent2-3a17f',
    storageBucket: 'easyrent2-3a17f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rHbjqEyqUf6z5TDBaVgi9XZNv7fdmW0',
    appId: '1:192956021233:ios:34311b97c60329df12ac50',
    messagingSenderId: '192956021233',
    projectId: 'easyrent2-3a17f',
    storageBucket: 'easyrent2-3a17f.firebasestorage.app',
    iosBundleId: 'com.example.easyrent2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rHbjqEyqUf6z5TDBaVgi9XZNv7fdmW0',
    appId: '1:192956021233:ios:34311b97c60329df12ac50',
    messagingSenderId: '192956021233',
    projectId: 'easyrent2-3a17f',
    storageBucket: 'easyrent2-3a17f.firebasestorage.app',
    iosBundleId: 'com.example.easyrent2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDELO4_6o0WQ2VGJBO1YO0sLgSYy0jfNWI',
    appId: '1:192956021233:web:736cefe57aef564f12ac50',
    messagingSenderId: '192956021233',
    projectId: 'easyrent2-3a17f',
    authDomain: 'easyrent2-3a17f.firebaseapp.com',
    storageBucket: 'easyrent2-3a17f.firebasestorage.app',
    measurementId: 'G-57K3QE4H99',
  );
}
