// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYUQNqOgR9_l2-10FkKoU7Kue0JH3HWU',
    appId: '1:819568481355:web:e180f34fc208d0d5b5e9ce',
    messagingSenderId: '819568481355',
    projectId: 'agriconnect-ba1f7',
    authDomain: 'agriconnect-ba1f7.firebaseapp.com',
    storageBucket: 'agriconnect-ba1f7.firebasestorage.app',
    measurementId: 'G-LKZXFFHX5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfRzO-rXWvFPUz2Hyv1XQxggrSCa5_dcY',
    appId: '1:819568481355:android:80f05a94116da1e4b5e9ce',
    messagingSenderId: '819568481355',
    projectId: 'agriconnect-ba1f7',
    storageBucket: 'agriconnect-ba1f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCItotOZuoqZ7U5kH1jMZTnABdc2w5lqZ4',
    appId: '1:819568481355:ios:3d270f8f51e087e2b5e9ce',
    messagingSenderId: '819568481355',
    projectId: 'agriconnect-ba1f7',
    storageBucket: 'agriconnect-ba1f7.firebasestorage.app',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCItotOZuoqZ7U5kH1jMZTnABdc2w5lqZ4',
    appId: '1:819568481355:ios:3d270f8f51e087e2b5e9ce',
    messagingSenderId: '819568481355',
    projectId: 'agriconnect-ba1f7',
    storageBucket: 'agriconnect-ba1f7.firebasestorage.app',
    iosBundleId: 'com.example.agriconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYUQNqOgR9_l2-10FkKoU7Kue0JH3HWU',
    appId: '1:819568481355:web:7fdae1239c6899d6b5e9ce',
    messagingSenderId: '819568481355',
    projectId: 'agriconnect-ba1f7',
    authDomain: 'agriconnect-ba1f7.firebaseapp.com',
    storageBucket: 'agriconnect-ba1f7.firebasestorage.app',
    measurementId: 'G-SWEHN264FE',
  );
}
