// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl15rqDFcwDbc246NmNnMNCJh9LdI6fFQ',
    appId: '1:805825530015:web:3833462769b40bf6a73aaa',
    messagingSenderId: '805825530015',
    projectId: 'my-farmerconnect-project',
    authDomain: 'my-farmerconnect-project.firebaseapp.com',
    storageBucket: 'my-farmerconnect-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEk3lUHajkvH8lIVEW-KRaVl2YQL-3IMI',
    appId: '1:805825530015:android:e9d0054001d1225ea73aaa',
    messagingSenderId: '805825530015',
    projectId: 'my-farmerconnect-project',
    storageBucket: 'my-farmerconnect-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjWLi5lqJHbOHS4V4uCyuVg2V1-Pk6efQ',
    appId: '1:805825530015:ios:35f69f3a19bb7e9da73aaa',
    messagingSenderId: '805825530015',
    projectId: 'my-farmerconnect-project',
    storageBucket: 'my-farmerconnect-project.firebasestorage.app',
    iosBundleId: 'com.example.farmerconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjWLi5lqJHbOHS4V4uCyuVg2V1-Pk6efQ',
    appId: '1:805825530015:ios:35f69f3a19bb7e9da73aaa',
    messagingSenderId: '805825530015',
    projectId: 'my-farmerconnect-project',
    storageBucket: 'my-farmerconnect-project.firebasestorage.app',
    iosBundleId: 'com.example.farmerconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl15rqDFcwDbc246NmNnMNCJh9LdI6fFQ',
    appId: '1:805825530015:web:8f3ba86b2dc60b73a73aaa',
    messagingSenderId: '805825530015',
    projectId: 'my-farmerconnect-project',
    authDomain: 'my-farmerconnect-project.firebaseapp.com',
    storageBucket: 'my-farmerconnect-project.firebasestorage.app',
  );
}
