// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1-XOMEYw98wrSLi62u4J_0oZaiLKPCs',
    appId: '1:804532614679:web:f39da04ff392809a37ce52',
    messagingSenderId: '804532614679',
    projectId: 'techbuy-a305f',
    authDomain: 'techbuy-a305f.firebaseapp.com',
    storageBucket: 'techbuy-a305f.firebasestorage.app',
    measurementId: 'G-5BY2D18QT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVIIPvr9dDbiaGGYR17U2SO4J06h2gOQw',
    appId: '1:804532614679:android:563f145436ea15ee37ce52',
    messagingSenderId: '804532614679',
    projectId: 'techbuy-a305f',
    storageBucket: 'techbuy-a305f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABOTr8R7q0d3ERN7Wr_cmDu0jfmL2corM',
    appId: '1:804532614679:ios:33d4cbdceed93dfd37ce52',
    messagingSenderId: '804532614679',
    projectId: 'techbuy-a305f',
    storageBucket: 'techbuy-a305f.firebasestorage.app',
    iosBundleId: 'com.example.techbuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABOTr8R7q0d3ERN7Wr_cmDu0jfmL2corM',
    appId: '1:804532614679:ios:33d4cbdceed93dfd37ce52',
    messagingSenderId: '804532614679',
    projectId: 'techbuy-a305f',
    storageBucket: 'techbuy-a305f.firebasestorage.app',
    iosBundleId: 'com.example.techbuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb1-XOMEYw98wrSLi62u4J_0oZaiLKPCs',
    appId: '1:804532614679:web:a4ab2c8cb012472337ce52',
    messagingSenderId: '804532614679',
    projectId: 'techbuy-a305f',
    authDomain: 'techbuy-a305f.firebaseapp.com',
    storageBucket: 'techbuy-a305f.firebasestorage.app',
    measurementId: 'G-VGCWWYSEQV',
  );
}
