name: esoma
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  url_launcher: ^6.1.10
  firebase_windows: ^0.0.7
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.5.0
  syncfusion_flutter_pdfviewer: ^30.1.39
  image_picker: ^1.0.4
  firebase_storage: ^12.4.9
  device_info_plus:
  firebase_analytics: ^11.5.2
  win32: ^5.14.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/momo.png
    - assets/paypal.png
    - assets/paytm.png
