// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4ifNq77-_R1PCPTsZZGEb7bYTrWdYbKA',
    appId: '1:874903627966:web:649f470e8df061be62d6ef',
    messagingSenderId: '874903627966',
    projectId: 'bankaccount-2025-30b5c',
    authDomain: 'bankaccount-2025-30b5c.firebaseapp.com',
    storageBucket: 'bankaccount-2025-30b5c.firebasestorage.app',
    measurementId: 'G-9J4XVCZESP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwitMco_KS1wD4Il3bKQYKtBq0fHVIkLc',
    appId: '1:874903627966:android:e2ac0797db518ba762d6ef',
    messagingSenderId: '874903627966',
    projectId: 'bankaccount-2025-30b5c',
    storageBucket: 'bankaccount-2025-30b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjHsVLxP7SC0OogoSjRqIs9NfPj9CKBI',
    appId: '1:874903627966:ios:8a557bc0fe02e67a62d6ef',
    messagingSenderId: '874903627966',
    projectId: 'bankaccount-2025-30b5c',
    storageBucket: 'bankaccount-2025-30b5c.firebasestorage.app',
    iosBundleId: 'com.example.bankAcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGjHsVLxP7SC0OogoSjRqIs9NfPj9CKBI',
    appId: '1:874903627966:ios:8a557bc0fe02e67a62d6ef',
    messagingSenderId: '874903627966',
    projectId: 'bankaccount-2025-30b5c',
    storageBucket: 'bankaccount-2025-30b5c.firebasestorage.app',
    iosBundleId: 'com.example.bankAcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4ifNq77-_R1PCPTsZZGEb7bYTrWdYbKA',
    appId: '1:874903627966:web:48c45a1cfd64089f62d6ef',
    messagingSenderId: '874903627966',
    projectId: 'bankaccount-2025-30b5c',
    authDomain: 'bankaccount-2025-30b5c.firebaseapp.com',
    storageBucket: 'bankaccount-2025-30b5c.firebasestorage.app',
    measurementId: 'G-S8MZ8NP52P',
  );

}