// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAgzIBEGDkxlVwAVVXPwi1UMDiPwZY420',
    appId: '1:490504695292:web:9266bd52e8fabb145e1679',
    messagingSenderId: '490504695292',
    projectId: 'bookswap-afa87',
    authDomain: 'bookswap-afa87.firebaseapp.com',
    storageBucket: 'bookswap-afa87.firebasestorage.app',
    measurementId: 'G-41PP8PX2ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzUuZ-AsPdPRFd5YWm_8nOG7qZdN1VskE',
    appId: '1:490504695292:android:6d13dba2338cc3c65e1679',
    messagingSenderId: '490504695292',
    projectId: 'bookswap-afa87',
    storageBucket: 'bookswap-afa87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCcg7uAZRrMwtzOMzJaRR_70ajA9RkO4Y',
    appId: '1:490504695292:ios:40eb97d0b8f087775e1679',
    messagingSenderId: '490504695292',
    projectId: 'bookswap-afa87',
    storageBucket: 'bookswap-afa87.firebasestorage.app',
    androidClientId: '490504695292-etsmdkl8r8cpp0e078nfjde1esela1jo.apps.googleusercontent.com',
    iosClientId: '490504695292-0db1n6enq6n9dmu2gdee2f1mjhuvb7u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCcg7uAZRrMwtzOMzJaRR_70ajA9RkO4Y',
    appId: '1:490504695292:ios:40eb97d0b8f087775e1679',
    messagingSenderId: '490504695292',
    projectId: 'bookswap-afa87',
    storageBucket: 'bookswap-afa87.firebasestorage.app',
    androidClientId: '490504695292-etsmdkl8r8cpp0e078nfjde1esela1jo.apps.googleusercontent.com',
    iosClientId: '490504695292-0db1n6enq6n9dmu2gdee2f1mjhuvb7u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAgzIBEGDkxlVwAVVXPwi1UMDiPwZY420',
    appId: '1:490504695292:web:4f3d919611856be45e1679',
    messagingSenderId: '490504695292',
    projectId: 'bookswap-afa87',
    authDomain: 'bookswap-afa87.firebaseapp.com',
    storageBucket: 'bookswap-afa87.firebasestorage.app',
    measurementId: 'G-GPLM0BDTR7',
  );
}
