// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPUKVN0quexR9mQsHRBH9TAnWPHvDTpjs',
    appId: '1:616444734280:web:b7d97d1556dbc2026be17d',
    messagingSenderId: '616444734280',
    projectId: 'vetmed-4a1a5',
    authDomain: 'vetmed-4a1a5.firebaseapp.com',
    storageBucket: 'vetmed-4a1a5.firebasestorage.app',
    measurementId: 'G-YSLBHDJRX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbPxIPYTJL12kLhAG1ypxRxMQ24SH4dy8',
    appId: '1:616444734280:android:4bff8f839d71cf7d6be17d',
    messagingSenderId: '616444734280',
    projectId: 'vetmed-4a1a5',
    storageBucket: 'vetmed-4a1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUL2FcHdO-eXmLd0i_bit5h0v_xP5uSYg',
    appId: '1:616444734280:ios:431563919efded646be17d',
    messagingSenderId: '616444734280',
    projectId: 'vetmed-4a1a5',
    storageBucket: 'vetmed-4a1a5.firebasestorage.app',
    iosBundleId: 'com.example.vetmed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUL2FcHdO-eXmLd0i_bit5h0v_xP5uSYg',
    appId: '1:616444734280:ios:431563919efded646be17d',
    messagingSenderId: '616444734280',
    projectId: 'vetmed-4a1a5',
    storageBucket: 'vetmed-4a1a5.firebasestorage.app',
    iosBundleId: 'com.example.vetmed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPUKVN0quexR9mQsHRBH9TAnWPHvDTpjs',
    appId: '1:616444734280:web:a10666da86ee9bcf6be17d',
    messagingSenderId: '616444734280',
    projectId: 'vetmed-4a1a5',
    authDomain: 'vetmed-4a1a5.firebaseapp.com',
    storageBucket: 'vetmed-4a1a5.firebasestorage.app',
    measurementId: 'G-X379CYND3V',
  );
}
