// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJiZMhqIh9Blg6pU8k9lmlFFdcFXtBpdA',
    appId: '1:381789807172:web:10d6444255852f62775211',
    messagingSenderId: '381789807172',
    projectId: 'ride-e61a7',
    authDomain: 'ride-e61a7.firebaseapp.com',
    storageBucket: 'ride-e61a7.firebasestorage.app',
    measurementId: 'G-J5TDRQXY92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrVvQJyznshY_1yI49tQJbnBdKwgB3QI4',
    appId: '1:381789807172:android:9a2ac608a2603ec1775211',
    messagingSenderId: '381789807172',
    projectId: 'ride-e61a7',
    storageBucket: 'ride-e61a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHvALpedSuIGK1irEzN118aLG6CtDd7rE',
    appId: '1:381789807172:ios:7c5f0d24be953df5775211',
    messagingSenderId: '381789807172',
    projectId: 'ride-e61a7',
    storageBucket: 'ride-e61a7.firebasestorage.app',
    iosBundleId: 'com.example.ride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHvALpedSuIGK1irEzN118aLG6CtDd7rE',
    appId: '1:381789807172:ios:7c5f0d24be953df5775211',
    messagingSenderId: '381789807172',
    projectId: 'ride-e61a7',
    storageBucket: 'ride-e61a7.firebasestorage.app',
    iosBundleId: 'com.example.ride',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJiZMhqIh9Blg6pU8k9lmlFFdcFXtBpdA',
    appId: '1:381789807172:web:065538c06719e488775211',
    messagingSenderId: '381789807172',
    projectId: 'ride-e61a7',
    authDomain: 'ride-e61a7.firebaseapp.com',
    storageBucket: 'ride-e61a7.firebasestorage.app',
    measurementId: 'G-T4WMJJ2C9F',
  );
}
