name: infofarmer

description: InfoFarmer mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  google_sign_in: ^6.1.5
  url_launcher: ^6.2.6
  js: ^0.6.7
  flutter_tts: ^3.8.5
  http: ^1.1.0
  image_picker: any
  share_plus: ^7.0.2
  flutter_local_notifications: ^14.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  geolocator: ^9.0.2
  google_mobile_ads: ^2.3.0
  connectivity_plus: ^4.0.2
  fl_chart: ^1.0.0
  flutter_svg: ^2.0.7
  # Add any other UI or utility packages you use
  in_app_purchase: ^3.1.11
  flutter_paypal: ^0.2.0
  flutterwave_standard: ^1.0.7
  universal_platform: ^1.0.0+1
  flutter_stripe: ^9.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/diseases/
    - assets/images/
