// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4ZRa93nuVxniZK2CjMTvhZSuyBMG-7I',
    appId: '1:413956223695:web:302a4041f1db97a4713dba',
    messagingSenderId: '413956223695',
    projectId: 'creditrack-c6966',
    authDomain: 'creditrack-c6966.firebaseapp.com',
    storageBucket: 'creditrack-c6966.firebasestorage.app',
    measurementId: 'G-RCCXQW8Z5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpYhye4etHSk6CBg1Vgg5arUVb-nRgqNo',
    appId: '1:413956223695:android:ae75f3be6f0e4134713dba',
    messagingSenderId: '413956223695',
    projectId: 'creditrack-c6966',
    storageBucket: 'creditrack-c6966.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNlhJLrM_GAnELkceraWEFN3-fSY3K9U',
    appId: '1:413956223695:ios:768bdef8af15a417713dba',
    messagingSenderId: '413956223695',
    projectId: 'creditrack-c6966',
    storageBucket: 'creditrack-c6966.firebasestorage.app',
    androidClientId: '413956223695-201aavrvu1mbalsei4a9rh1b3b9q49eb.apps.googleusercontent.com',
    iosClientId: '413956223695-ak24ln0baidb4dp5nrtusfmsv4egrkoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwNlhJLrM_GAnELkceraWEFN3-fSY3K9U',
    appId: '1:413956223695:ios:768bdef8af15a417713dba',
    messagingSenderId: '413956223695',
    projectId: 'creditrack-c6966',
    storageBucket: 'creditrack-c6966.firebasestorage.app',
    androidClientId: '413956223695-201aavrvu1mbalsei4a9rh1b3b9q49eb.apps.googleusercontent.com',
    iosClientId: '413956223695-ak24ln0baidb4dp5nrtusfmsv4egrkoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.creditrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG4ZRa93nuVxniZK2CjMTvhZSuyBMG-7I',
    appId: '1:413956223695:web:ad8f9f23ae0373ec713dba',
    messagingSenderId: '413956223695',
    projectId: 'creditrack-c6966',
    authDomain: 'creditrack-c6966.firebaseapp.com',
    storageBucket: 'creditrack-c6966.firebasestorage.app',
    measurementId: 'G-BP9P7HL6DR',
  );
}
