// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOHPUX-EB2sFgz3YST_YImZqbF2t8Ddu0',
    appId: '1:487150172655:web:91cac8767dfc806bf8de1a',
    messagingSenderId: '487150172655',
    projectId: 'aquatrack-9782f',
    authDomain: 'aquatrack-9782f.firebaseapp.com',
    storageBucket: 'aquatrack-9782f.firebasestorage.app',
    measurementId: 'G-GB139WK5Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYneVJ4iYEbSn04wBLNkjpPxUQJGtwfs',
    appId: '1:487150172655:android:b0b415884deb1aa7f8de1a',
    messagingSenderId: '487150172655',
    projectId: 'aquatrack-9782f',
    storageBucket: 'aquatrack-9782f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5EAKagoo_WRT2mPcdV6Uo100nw9ndHCw',
    appId: '1:487150172655:ios:5d201abd9eed47cdf8de1a',
    messagingSenderId: '487150172655',
    projectId: 'aquatrack-9782f',
    storageBucket: 'aquatrack-9782f.firebasestorage.app',
    iosBundleId: 'com.example.aquatrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5EAKagoo_WRT2mPcdV6Uo100nw9ndHCw',
    appId: '1:487150172655:ios:5d201abd9eed47cdf8de1a',
    messagingSenderId: '487150172655',
    projectId: 'aquatrack-9782f',
    storageBucket: 'aquatrack-9782f.firebasestorage.app',
    iosBundleId: 'com.example.aquatrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOHPUX-EB2sFgz3YST_YImZqbF2t8Ddu0',
    appId: '1:487150172655:web:8f7ce56fda706fc7f8de1a',
    messagingSenderId: '487150172655',
    projectId: 'aquatrack-9782f',
    authDomain: 'aquatrack-9782f.firebaseapp.com',
    storageBucket: 'aquatrack-9782f.firebasestorage.app',
    measurementId: 'G-7RV72QX8M4',
  );

}