// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJs-wbns3rpEXxceDCxz2sHuhgdhBBNK8',
    appId: '1:67912551300:web:e5a9313361009cfd3b6bd1',
    messagingSenderId: '67912551300',
    projectId: 'edumanage-31cd3',
    authDomain: 'edumanage-31cd3.firebaseapp.com',
    storageBucket: 'edumanage-31cd3.firebasestorage.app',
    measurementId: 'G-23286HMMS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmlyBc9Sbws04XR6TQDFQkgg1A8xQqtbs',
    appId: '1:67912551300:android:df7e2986ca50ae463b6bd1',
    messagingSenderId: '67912551300',
    projectId: 'edumanage-31cd3',
    storageBucket: 'edumanage-31cd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCECHzCapcqGtLut2QoKPs0iezENr55sQ',
    appId: '1:67912551300:ios:04d0fc5dc2d073963b6bd1',
    messagingSenderId: '67912551300',
    projectId: 'edumanage-31cd3',
    storageBucket: 'edumanage-31cd3.firebasestorage.app',
    androidClientId: '67912551300-h0ftig6kgeblm679rodb70357mdir83o.apps.googleusercontent.com',
    iosClientId: '67912551300-qn718s2dft2cms7b7vfq0vrruens8vh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.edumanage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCECHzCapcqGtLut2QoKPs0iezENr55sQ',
    appId: '1:67912551300:ios:04d0fc5dc2d073963b6bd1',
    messagingSenderId: '67912551300',
    projectId: 'edumanage-31cd3',
    storageBucket: 'edumanage-31cd3.firebasestorage.app',
    androidClientId: '67912551300-h0ftig6kgeblm679rodb70357mdir83o.apps.googleusercontent.com',
    iosClientId: '67912551300-qn718s2dft2cms7b7vfq0vrruens8vh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.edumanage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJs-wbns3rpEXxceDCxz2sHuhgdhBBNK8',
    appId: '1:67912551300:web:811ddf738905de863b6bd1',
    messagingSenderId: '67912551300',
    projectId: 'edumanage-31cd3',
    authDomain: 'edumanage-31cd3.firebaseapp.com',
    storageBucket: 'edumanage-31cd3.firebasestorage.app',
    measurementId: 'G-VRQV28QPZV',
  );

}