// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9gRIR35EFIWmtzcncyOe0Fr-zwwtGqE',
    appId: '1:785790233579:web:56043b6dd36002442e07ae',
    messagingSenderId: '785790233579',
    projectId: 'rwandaread',
    authDomain: 'rwandaread.firebaseapp.com',
    storageBucket: 'rwandaread.firebasestorage.app',
    measurementId: 'G-4ZXQ6M0BBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACZvuQSzQa4hp2oV8l1SjlDcub9_75LY0',
    appId: '1:785790233579:android:6b05750632255c232e07ae',
    messagingSenderId: '785790233579',
    projectId: 'rwandaread',
    storageBucket: 'rwandaread.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP0w8vD5aJl_sQJ3mslUtJsFYtENsY5bY',
    appId: '1:785790233579:ios:f8d49b58d4826d5f2e07ae',
    messagingSenderId: '785790233579',
    projectId: 'rwandaread',
    storageBucket: 'rwandaread.firebasestorage.app',
    iosBundleId: 'com.example.rwandaread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP0w8vD5aJl_sQJ3mslUtJsFYtENsY5bY',
    appId: '1:785790233579:ios:f8d49b58d4826d5f2e07ae',
    messagingSenderId: '785790233579',
    projectId: 'rwandaread',
    storageBucket: 'rwandaread.firebasestorage.app',
    iosBundleId: 'com.example.rwandaread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv9gRIR35EFIWmtzcncyOe0Fr-zwwtGqE',
    appId: '1:785790233579:web:db8ae4a29ccdd7442e07ae',
    messagingSenderId: '785790233579',
    projectId: 'rwandaread',
    authDomain: 'rwandaread.firebaseapp.com',
    storageBucket: 'rwandaread.firebasestorage.app',
    measurementId: 'G-DCZ3M24ZC9',
  );
}
