// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6UlAv9nQkQTYLRIJsJCfTasNYy6p-trg',
    appId: '1:267926257288:web:9a31940f98a710cf56a93d',
    messagingSenderId: '267926257288',
    projectId: 'skillslinks-17b63',
    authDomain: 'skillslinks-17b63.firebaseapp.com',
    storageBucket: 'skillslinks-17b63.firebasestorage.app',
    measurementId: 'G-XQM790HDLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYMktw1MnZj1rff9n92B4bFe6gJARw4l0',
    appId: '1:267926257288:android:018e3f0846fdc2dc56a93d',
    messagingSenderId: '267926257288',
    projectId: 'skillslinks-17b63',
    storageBucket: 'skillslinks-17b63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL1Cv4aQcEkbP2cwZEzvm7JHASthS_NcI',
    appId: '1:267926257288:ios:050195d87d665a7b56a93d',
    messagingSenderId: '267926257288',
    projectId: 'skillslinks-17b63',
    storageBucket: 'skillslinks-17b63.firebasestorage.app',
    iosBundleId: 'com.example.skillslinks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL1Cv4aQcEkbP2cwZEzvm7JHASthS_NcI',
    appId: '1:267926257288:ios:050195d87d665a7b56a93d',
    messagingSenderId: '267926257288',
    projectId: 'skillslinks-17b63',
    storageBucket: 'skillslinks-17b63.firebasestorage.app',
    iosBundleId: 'com.example.skillslinks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6UlAv9nQkQTYLRIJsJCfTasNYy6p-trg',
    appId: '1:267926257288:web:54845048fc475b3056a93d',
    messagingSenderId: '267926257288',
    projectId: 'skillslinks-17b63',
    authDomain: 'skillslinks-17b63.firebaseapp.com',
    storageBucket: 'skillslinks-17b63.firebasestorage.app',
    measurementId: 'G-4PME12G0ZD',
  );
}
