// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrazpMzhz5f85YDu0DedjIl0XKi1NaaPQ',
    appId: '1:1021910036167:web:761002cf11c601f47498e2',
    messagingSenderId: '1021910036167',
    projectId: 'saferide-65c14',
    authDomain: 'saferide-65c14.firebaseapp.com',
    storageBucket: 'saferide-65c14.firebasestorage.app',
    measurementId: 'G-XK6HKSZKRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzQfhCrTzURWAKqvG6sVf5lUejiqQdxJA',
    appId: '1:1021910036167:android:3ca0886886d2f33d7498e2',
    messagingSenderId: '1021910036167',
    projectId: 'saferide-65c14',
    storageBucket: 'saferide-65c14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjQ44RJHGhdt-R_vBcq0LK7XW2FcTwkkY',
    appId: '1:1021910036167:ios:c785e9744f25d2517498e2',
    messagingSenderId: '1021910036167',
    projectId: 'saferide-65c14',
    storageBucket: 'saferide-65c14.firebasestorage.app',
    iosClientId: '1021910036167-bhmkravnr2v2aoqilfqor7d7elvqm1hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjQ44RJHGhdt-R_vBcq0LK7XW2FcTwkkY',
    appId: '1:1021910036167:ios:c785e9744f25d2517498e2',
    messagingSenderId: '1021910036167',
    projectId: 'saferide-65c14',
    storageBucket: 'saferide-65c14.firebasestorage.app',
    iosClientId: '1021910036167-bhmkravnr2v2aoqilfqor7d7elvqm1hs.apps.googleusercontent.com',
    iosBundleId: 'com.example.saferide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrazpMzhz5f85YDu0DedjIl0XKi1NaaPQ',
    appId: '1:1021910036167:web:5a80b05d0d7168b07498e2',
    messagingSenderId: '1021910036167',
    projectId: 'saferide-65c14',
    authDomain: 'saferide-65c14.firebaseapp.com',
    storageBucket: 'saferide-65c14.firebasestorage.app',
    measurementId: 'G-S9TZDH3WHY',
  );

}