// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0HpnPZvtq2g6-uv3CNZ48vcFXmwvLeYQ',
    appId: '1:584622126053:web:4bd191ed98eed19987b50c',
    messagingSenderId: '584622126053',
    projectId: 'rp03049-2f84b',
    authDomain: 'rp03049-2f84b.firebaseapp.com',
    storageBucket: 'rp03049-2f84b.firebasestorage.app',
    measurementId: 'G-K4HCEMVLET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXPduQMzyT5W9UFFLwWHV_KJySVXhHZUI',
    appId: '1:584622126053:android:fe0a2d38db406fb787b50c',
    messagingSenderId: '584622126053',
    projectId: 'rp03049-2f84b',
    storageBucket: 'rp03049-2f84b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWgbLUG7unjNdSg0S52TmpwUtkxf-pwl0',
    appId: '1:584622126053:ios:813c3f08402ec5cb87b50c',
    messagingSenderId: '584622126053',
    projectId: 'rp03049-2f84b',
    storageBucket: 'rp03049-2f84b.firebasestorage.app',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWgbLUG7unjNdSg0S52TmpwUtkxf-pwl0',
    appId: '1:584622126053:ios:813c3f08402ec5cb87b50c',
    messagingSenderId: '584622126053',
    projectId: 'rp03049-2f84b',
    storageBucket: 'rp03049-2f84b.firebasestorage.app',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0HpnPZvtq2g6-uv3CNZ48vcFXmwvLeYQ',
    appId: '1:584622126053:web:e17637193e190f7587b50c',
    messagingSenderId: '584622126053',
    projectId: 'rp03049-2f84b',
    authDomain: 'rp03049-2f84b.firebaseapp.com',
    storageBucket: 'rp03049-2f84b.firebasestorage.app',
    measurementId: 'G-53PMKJ1T9Q',
  );
}
