// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMoDoQHBmcEyiJTYQXT9PDjUa7hK9oXM',
    appId: '1:672115633724:web:0db6ac870526f5daa0dd39',
    messagingSenderId: '672115633724',
    projectId: 'jobportal-73415',
    authDomain: 'jobportal-73415.firebaseapp.com',
    storageBucket: 'jobportal-73415.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBneiI58iM2l0E8fh_mb1AngZt9KuZh9zs',
    appId: '1:672115633724:android:b096f8bd0ce1c2c2a0dd39',
    messagingSenderId: '672115633724',
    projectId: 'jobportal-73415',
    storageBucket: 'jobportal-73415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkfNS0zmF0nqQbin-vRVaNByr49uKwZU8',
    appId: '1:672115633724:ios:054e1df81407bafba0dd39',
    messagingSenderId: '672115633724',
    projectId: 'jobportal-73415',
    storageBucket: 'jobportal-73415.firebasestorage.app',
    iosBundleId: 'com.example.jobportal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkfNS0zmF0nqQbin-vRVaNByr49uKwZU8',
    appId: '1:672115633724:ios:054e1df81407bafba0dd39',
    messagingSenderId: '672115633724',
    projectId: 'jobportal-73415',
    storageBucket: 'jobportal-73415.firebasestorage.app',
    iosBundleId: 'com.example.jobportal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMoDoQHBmcEyiJTYQXT9PDjUa7hK9oXM',
    appId: '1:672115633724:web:a14b880f6581fdd8a0dd39',
    messagingSenderId: '672115633724',
    projectId: 'jobportal-73415',
    authDomain: 'jobportal-73415.firebaseapp.com',
    storageBucket: 'jobportal-73415.firebasestorage.app',
  );
}
