// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASesFS2czUKIPadYWgB_A344UmiQY8THU',
    appId: '1:931368824138:web:7667c80dbcdf315d8a25b3',
    messagingSenderId: '931368824138',
    projectId: 'locallink-b473d',
    authDomain: 'locallink-b473d.firebaseapp.com',
    storageBucket: 'locallink-b473d.firebasestorage.app',
    measurementId: 'G-HGMFWBYQJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASesFS2czUKIPadYWgB_A344UmiQY8THU',
    appId: '1:931368824138:android:baf8d6e94f20260f8a25b3',
    messagingSenderId: '931368824138',
    projectId: 'locallink-b473d',
    storageBucket: 'locallink-b473d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASesFS2czUKIPadYWgB_A344UmiQY8THU',
    appId: '1:931368824138:ios:ef770dc0f267841d8a25b3',
    messagingSenderId: '931368824138',
    projectId: 'locallink-b473d',
    storageBucket: 'locallink-b473d.firebasestorage.app',
    iosBundleId: 'com.example.localLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASesFS2czUKIPadYWgB_A344UmiQY8THU',
    appId: '1:931368824138:ios:ef770dc0f267841d8a25b3',
    messagingSenderId: '931368824138',
    projectId: 'locallink-b473d',
    storageBucket: 'locallink-b473d.firebasestorage.app',
    iosBundleId: 'com.example.localLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASesFS2czUKIPadYWgB_A344UmiQY8THU',
    appId: '1:931368824138:web:f52576f8419da2438a25b3',
    messagingSenderId: '931368824138',
    projectId: 'locallink-b473d',
    authDomain: 'locallink-b473d.firebaseapp.com',
    storageBucket: 'locallink-b473d.firebasestorage.app',
    measurementId: 'G-9CK3WVF6KV',
  );

}