// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeWxV8CqEjikURuZ2hmmNmwbiphqnwRUo',
    appId: '1:912745304601:web:de61d2e4409e8d68239088',
    messagingSenderId: '912745304601',
    projectId: 'booktalent-7c3d6',
    authDomain: 'booktalent-7c3d6.firebaseapp.com',
    storageBucket: 'booktalent-7c3d6.firebasestorage.app',
    measurementId: 'G-PWHG9NNV4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8MQkbAhS2WULoNJtJVsNM8rhSyMWwlUc',
    appId: '1:912745304601:android:4a60ed98890fa6f1239088',
    messagingSenderId: '912745304601',
    projectId: 'booktalent-7c3d6',
    storageBucket: 'booktalent-7c3d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCii18tPBkeXlPLrZN0td85BVxb8yzD86A',
    appId: '1:912745304601:ios:07688a3a0aa70757239088',
    messagingSenderId: '912745304601',
    projectId: 'booktalent-7c3d6',
    storageBucket: 'booktalent-7c3d6.firebasestorage.app',
    androidClientId: '912745304601-2qnbf8c4mu8nsj4qqe53ft0iemihke2l.apps.googleusercontent.com',
    iosClientId: '912745304601-8stef28ldspuun3olha2375ubarap346.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmytalent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCii18tPBkeXlPLrZN0td85BVxb8yzD86A',
    appId: '1:912745304601:ios:07688a3a0aa70757239088',
    messagingSenderId: '912745304601',
    projectId: 'booktalent-7c3d6',
    storageBucket: 'booktalent-7c3d6.firebasestorage.app',
    androidClientId: '912745304601-2qnbf8c4mu8nsj4qqe53ft0iemihke2l.apps.googleusercontent.com',
    iosClientId: '912745304601-8stef28ldspuun3olha2375ubarap346.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmytalent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeWxV8CqEjikURuZ2hmmNmwbiphqnwRUo',
    appId: '1:912745304601:web:107459fdef8562a6239088',
    messagingSenderId: '912745304601',
    projectId: 'booktalent-7c3d6',
    authDomain: 'booktalent-7c3d6.firebaseapp.com',
    storageBucket: 'booktalent-7c3d6.firebasestorage.app',
    measurementId: 'G-9MT7C7NHFW',
  );

}