// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR7srpu8CIrrYtu4xBmUBZYp_UQ5IrUJM',
    appId: '1:959883641736:web:45488be4ab19ccfd73703d',
    messagingSenderId: '959883641736',
    projectId: 'rwanda-betting',
    authDomain: 'rwanda-betting.firebaseapp.com',
    storageBucket: 'rwanda-betting.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEraN_kF78WvdEFm5ChRYf8m5rUrP7NGU',
    appId: '1:959883641736:android:1695a914bc1295a473703d',
    messagingSenderId: '959883641736',
    projectId: 'rwanda-betting',
    storageBucket: 'rwanda-betting.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9tTWgps5Uy1W50Xey0hI-dHAAjSdhcdQ',
    appId: '1:959883641736:ios:92bfc7b49353f36b73703d',
    messagingSenderId: '959883641736',
    projectId: 'rwanda-betting',
    storageBucket: 'rwanda-betting.firebasestorage.app',
    iosBundleId: 'com.example.betnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9tTWgps5Uy1W50Xey0hI-dHAAjSdhcdQ',
    appId: '1:959883641736:ios:92bfc7b49353f36b73703d',
    messagingSenderId: '959883641736',
    projectId: 'rwanda-betting',
    storageBucket: 'rwanda-betting.firebasestorage.app',
    iosBundleId: 'com.example.betnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR7srpu8CIrrYtu4xBmUBZYp_UQ5IrUJM',
    appId: '1:959883641736:web:26d9060d8a682c2d73703d',
    messagingSenderId: '959883641736',
    projectId: 'rwanda-betting',
    authDomain: 'rwanda-betting.firebaseapp.com',
    storageBucket: 'rwanda-betting.firebasestorage.app',
  );
}
