// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIr65CrdA8-riWymwK6dULEefbkjz8uP0',
    appId: '1:943855848485:web:c596ef03b02391dcce83cc',
    messagingSenderId: '943855848485',
    projectId: 'rp03060-c430a',
    authDomain: 'rp03060-c430a.firebaseapp.com',
    storageBucket: 'rp03060-c430a.firebasestorage.app',
    measurementId: 'G-GDLZM16P63',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRZfCW9YrxIh-te0tn4MXhQ3hzLGVJfvY',
    appId: '1:943855848485:android:7e6f0efeaedab4e5ce83cc',
    messagingSenderId: '943855848485',
    projectId: 'rp03060-c430a',
    storageBucket: 'rp03060-c430a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVV8xj_8Tg8ljbU_2e06VseouSCa5crTY',
    appId: '1:943855848485:ios:30727a113bbd7f1cce83cc',
    messagingSenderId: '943855848485',
    projectId: 'rp03060-c430a',
    storageBucket: 'rp03060-c430a.firebasestorage.app',
    iosBundleId: 'com.example.22rp03060',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVV8xj_8Tg8ljbU_2e06VseouSCa5crTY',
    appId: '1:943855848485:ios:30727a113bbd7f1cce83cc',
    messagingSenderId: '943855848485',
    projectId: 'rp03060-c430a',
    storageBucket: 'rp03060-c430a.firebasestorage.app',
    iosBundleId: 'com.example.22rp03060',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIr65CrdA8-riWymwK6dULEefbkjz8uP0',
    appId: '1:943855848485:web:3b2b89ea8cfe8225ce83cc',
    messagingSenderId: '943855848485',
    projectId: 'rp03060-c430a',
    authDomain: 'rp03060-c430a.firebaseapp.com',
    storageBucket: 'rp03060-c430a.firebasestorage.app',
    measurementId: 'G-QY8S69X7SZ',
  );
}
