// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo0h3hNMYs3K-kSm-K-g9m9VjUAEzpqcY',
    appId: '1:1028972990348:web:9ed70ed7ac4d07db3890a9',
    messagingSenderId: '1028972990348',
    projectId: 'my-budgetwise-app-sandrine',
    authDomain: 'my-budgetwise-app-sandrine.firebaseapp.com',
    storageBucket: 'my-budgetwise-app-sandrine.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQsYP3z7rW3vmv4SU7Wn5ZCrO5EnoQkI',
    appId: '1:1028972990348:android:06250f2bc069d57e3890a9',
    messagingSenderId: '1028972990348',
    projectId: 'my-budgetwise-app-sandrine',
    storageBucket: 'my-budgetwise-app-sandrine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_mgnyngAuTorZ7Nmhz8B5x9SoZoq0fU',
    appId: '1:1028972990348:ios:f0e0b08605eda4e83890a9',
    messagingSenderId: '1028972990348',
    projectId: 'my-budgetwise-app-sandrine',
    storageBucket: 'my-budgetwise-app-sandrine.appspot.com',
    iosBundleId: 'com.example.budgetwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_mgnyngAuTorZ7Nmhz8B5x9SoZoq0fU',
    appId: '1:1028972990348:ios:f0e0b08605eda4e83890a9',
    messagingSenderId: '1028972990348',
    projectId: 'my-budgetwise-app-sandrine',
    storageBucket: 'my-budgetwise-app-sandrine.appspot.com',
    iosBundleId: 'com.example.budgetwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo0h3hNMYs3K-kSm-K-g9m9VjUAEzpqcY',
    appId: '1:1028972990348:web:0a7d76894db7503f3890a9',
    messagingSenderId: '1028972990348',
    projectId: 'my-budgetwise-app-sandrine',
    authDomain: 'my-budgetwise-app-sandrine.firebaseapp.com',
    storageBucket: 'my-budgetwise-app-sandrine.appspot.com',
  );
}
