// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGkLmXf3TEFUzYN4iTNaZssXjAHcPSshw',
    appId: '1:863579991529:web:8fde083a0be53925cb6f78',
    messagingSenderId: '863579991529',
    projectId: 'umuhinzismart',
    authDomain: 'umuhinzismart.firebaseapp.com',
    storageBucket: 'umuhinzismart.firebasestorage.app',
    measurementId: 'G-9CFVHE84CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfW54iOsEJMAWJyhOvJb-RSgA121aUVP4',
    appId: '1:863579991529:android:567931498b84fb2ecb6f78',
    messagingSenderId: '863579991529',
    projectId: 'umuhinzismart',
    storageBucket: 'umuhinzismart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7nLslgum_5TccLMRIvxt0v9-2lO8kpSc',
    appId: '1:863579991529:ios:50f663efbd0a834acb6f78',
    messagingSenderId: '863579991529',
    projectId: 'umuhinzismart',
    storageBucket: 'umuhinzismart.firebasestorage.app',
    iosBundleId: 'com.example.umuhinzismart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7nLslgum_5TccLMRIvxt0v9-2lO8kpSc',
    appId: '1:863579991529:ios:50f663efbd0a834acb6f78',
    messagingSenderId: '863579991529',
    projectId: 'umuhinzismart',
    storageBucket: 'umuhinzismart.firebasestorage.app',
    iosBundleId: 'com.example.umuhinzismart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGkLmXf3TEFUzYN4iTNaZssXjAHcPSshw',
    appId: '1:863579991529:web:c9fb770d62e5e1bfcb6f78',
    messagingSenderId: '863579991529',
    projectId: 'umuhinzismart',
    authDomain: 'umuhinzismart.firebaseapp.com',
    storageBucket: 'umuhinzismart.firebasestorage.app',
    measurementId: 'G-R8N4XSL1RX',
  );

} 