// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuzeeWlcgoxKwKXmRuzfA9QU8eHdEXEfw',
    appId: '1:320050492235:web:1715a6e0587a441fb0eece',
    messagingSenderId: '320050492235',
    projectId: 'budgetwise-98ee2',
    authDomain: 'budgetwise-98ee2.firebaseapp.com',
    storageBucket: 'budgetwise-98ee2.firebasestorage.app',
    measurementId: 'G-HG033CX2PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KtoJensACL3Q2gTFJJ-lA0vzpiYSXSw',
    appId: '1:320050492235:android:e02e358f4d24d6d7b0eece',
    messagingSenderId: '320050492235',
    projectId: 'budgetwise-98ee2',
    storageBucket: 'budgetwise-98ee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpOemujvDfKjyp4wza5y47Hr7XqRv_9LM',
    appId: '1:320050492235:ios:c335996b149f2943b0eece',
    messagingSenderId: '320050492235',
    projectId: 'budgetwise-98ee2',
    storageBucket: 'budgetwise-98ee2.firebasestorage.app',
    iosBundleId: 'com.example.budgetwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpOemujvDfKjyp4wza5y47Hr7XqRv_9LM',
    appId: '1:320050492235:ios:c335996b149f2943b0eece',
    messagingSenderId: '320050492235',
    projectId: 'budgetwise-98ee2',
    storageBucket: 'budgetwise-98ee2.firebasestorage.app',
    iosBundleId: 'com.example.budgetwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuzeeWlcgoxKwKXmRuzfA9QU8eHdEXEfw',
    appId: '1:320050492235:web:7c6abd3752c07f52b0eece',
    messagingSenderId: '320050492235',
    projectId: 'budgetwise-98ee2',
    authDomain: 'budgetwise-98ee2.firebaseapp.com',
    storageBucket: 'budgetwise-98ee2.firebasestorage.app',
    measurementId: 'G-X3YNDG4VEF',
  );
}
