// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRL0mRgh22vUqjRqSOZsOkVdzvUg2O_VA',
    appId: '1:695793636163:web:3c0b9f3a4b4a3970e8d5f6',
    messagingSenderId: '695793636163',
    projectId: 'midi-link-smartcare',
    authDomain: 'midi-link-smartcare.firebaseapp.com',
    storageBucket: 'midi-link-smartcare.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH313BL7OvHJLnqkVDbGt4KrXkzmrc4Kc',
    appId: '1:695793636163:android:0e845c8847366118e8d5f6',
    messagingSenderId: '695793636163',
    projectId: 'midi-link-smartcare',
    storageBucket: 'midi-link-smartcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqcg53uYsHPYflbaLeS4HYwfyuur4Lkt0',
    appId: '1:695793636163:ios:e9ee62e87eb2c283e8d5f6',
    messagingSenderId: '695793636163',
    projectId: 'midi-link-smartcare',
    storageBucket: 'midi-link-smartcare.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqcg53uYsHPYflbaLeS4HYwfyuur4Lkt0',
    appId: '1:695793636163:ios:e9ee62e87eb2c283e8d5f6',
    messagingSenderId: '695793636163',
    projectId: 'midi-link-smartcare',
    storageBucket: 'midi-link-smartcare.firebasestorage.app',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRL0mRgh22vUqjRqSOZsOkVdzvUg2O_VA',
    appId: '1:695793636163:web:6067475563cd5e75e8d5f6',
    messagingSenderId: '695793636163',
    projectId: 'midi-link-smartcare',
    authDomain: 'midi-link-smartcare.firebaseapp.com',
    storageBucket: 'midi-link-smartcare.firebasestorage.app',
  );
}
