// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ggxpc4T4c7hD9_WSlmqbdz4747kFio4',
    appId: '1:914505470510:web:7093e9b0b20788536b45bf',
    messagingSenderId: '914505470510',
    projectId: 'safarigo-61195',
    authDomain: 'safarigo-61195.firebaseapp.com',
    storageBucket: 'safarigo-61195.firebasestorage.app',
    measurementId: 'G-HVTRZHQ33Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRXzzvVvc7OsDw1NWxnOK2sjklQ-w_KI',
    appId: '1:914505470510:android:c1c1c0ca011d5b166b45bf',
    messagingSenderId: '914505470510',
    projectId: 'safarigo-61195',
    storageBucket: 'safarigo-61195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW2ptlqerOBeDrAiEF6eM5SGeGjLejYRI',
    appId: '1:914505470510:ios:b357f9bd113ec2526b45bf',
    messagingSenderId: '914505470510',
    projectId: 'safarigo-61195',
    storageBucket: 'safarigo-61195.firebasestorage.app',
    iosBundleId: 'com.example.safarigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW2ptlqerOBeDrAiEF6eM5SGeGjLejYRI',
    appId: '1:914505470510:ios:b357f9bd113ec2526b45bf',
    messagingSenderId: '914505470510',
    projectId: 'safarigo-61195',
    storageBucket: 'safarigo-61195.firebasestorage.app',
    iosBundleId: 'com.example.safarigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Ggxpc4T4c7hD9_WSlmqbdz4747kFio4',
    appId: '1:914505470510:web:71095bf05075eeed6b45bf',
    messagingSenderId: '914505470510',
    projectId: 'safarigo-61195',
    authDomain: 'safarigo-61195.firebaseapp.com',
    storageBucket: 'safarigo-61195.firebasestorage.app',
    measurementId: 'G-JPXXSX208Y',
  );
}
