// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkp5aC8sveJljvoIVEnaiiR7xLML4t1-0',
    appId: '1:535460033145:web:19053ef107c6faf77c1aa8',
    messagingSenderId: '535460033145',
    projectId: 'umutoninovelsstore',
    authDomain: 'umutoninovelsstore.firebaseapp.com',
    storageBucket: 'umutoninovelsstore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu0tfWOhO53h3XqSiwUIck35OixNmUy44',
    appId: '1:535460033145:android:78c523919c8f7deb7c1aa8',
    messagingSenderId: '535460033145',
    projectId: 'umutoninovelsstore',
    storageBucket: 'umutoninovelsstore.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5i2nIct243bbQ665aHOuwLD_NQjV_ly0',
    appId: '1:535460033145:ios:dc8a7d05ed6a5e317c1aa8',
    messagingSenderId: '535460033145',
    projectId: 'umutoninovelsstore',
    storageBucket: 'umutoninovelsstore.firebasestorage.app',
    iosBundleId: 'com.example.umutoniNovelsStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5i2nIct243bbQ665aHOuwLD_NQjV_ly0',
    appId: '1:535460033145:ios:dc8a7d05ed6a5e317c1aa8',
    messagingSenderId: '535460033145',
    projectId: 'umutoninovelsstore',
    storageBucket: 'umutoninovelsstore.firebasestorage.app',
    iosBundleId: 'com.example.umutoniNovelsStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkp5aC8sveJljvoIVEnaiiR7xLML4t1-0',
    appId: '1:535460033145:web:21b1e31c2347c4c67c1aa8',
    messagingSenderId: '535460033145',
    projectId: 'umutoninovelsstore',
    authDomain: 'umutoninovelsstore.firebaseapp.com',
    storageBucket: 'umutoninovelsstore.firebasestorage.app',
  );
}
