// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTG-EUH1he_DMm5YYd04Ncf-9cHwLyBMc',
    appId: '1:820522109690:web:b2cfc276e453ba9d78d743',
    messagingSenderId: '820522109690',
    projectId: 'isokoconnect-1f836',
    authDomain: 'isokoconnect-1f836.firebaseapp.com',
    storageBucket: 'isokoconnect-1f836.firebasestorage.app',
    measurementId: 'G-HG28F6WDK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOf4UK2YSLEuyIf-9tJWvQhMTc-fjWO_w',
    appId: '1:820522109690:android:34689026103ce3e378d743',
    messagingSenderId: '820522109690',
    projectId: 'isokoconnect-1f836',
    storageBucket: 'isokoconnect-1f836.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMWtlXAWTme0_tmCXPd3_DArstLg72LrI',
    appId: '1:820522109690:ios:80c204210af9824878d743',
    messagingSenderId: '820522109690',
    projectId: 'isokoconnect-1f836',
    storageBucket: 'isokoconnect-1f836.firebasestorage.app',
    iosBundleId: 'com.example.isokoconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMWtlXAWTme0_tmCXPd3_DArstLg72LrI',
    appId: '1:820522109690:ios:80c204210af9824878d743',
    messagingSenderId: '820522109690',
    projectId: 'isokoconnect-1f836',
    storageBucket: 'isokoconnect-1f836.firebasestorage.app',
    iosBundleId: 'com.example.isokoconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTG-EUH1he_DMm5YYd04Ncf-9cHwLyBMc',
    appId: '1:820522109690:web:824712fe899eabae78d743',
    messagingSenderId: '820522109690',
    projectId: 'isokoconnect-1f836',
    authDomain: 'isokoconnect-1f836.firebaseapp.com',
    storageBucket: 'isokoconnect-1f836.firebasestorage.app',
    measurementId: 'G-5CT35W9WLH',
  );
}
