// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTpY9ypjgfVHn0E5_9wiwbOlQwQ2c4Qnk',
    appId: '1:850791330193:web:6534398a31e8da26efea30',
    messagingSenderId: '850791330193',
    projectId: 'my-cleanconnect-app',
    authDomain: 'my-cleanconnect-app.firebaseapp.com',
    storageBucket: 'my-cleanconnect-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Nu1-FLhgxuaz0JzXiElDyZTt4JlaV74',
    appId: '1:850791330193:android:d8043577fcb6f84defea30',
    messagingSenderId: '850791330193',
    projectId: 'my-cleanconnect-app',
    storageBucket: 'my-cleanconnect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmtOE8ZpRnZFj5O8JYUv28kaBLw8sbrN4',
    appId: '1:850791330193:ios:56a5ddc6f0880f9defea30',
    messagingSenderId: '850791330193',
    projectId: 'my-cleanconnect-app',
    storageBucket: 'my-cleanconnect-app.firebasestorage.app',
    iosBundleId: 'com.example.cleanconnectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmtOE8ZpRnZFj5O8JYUv28kaBLw8sbrN4',
    appId: '1:850791330193:ios:56a5ddc6f0880f9defea30',
    messagingSenderId: '850791330193',
    projectId: 'my-cleanconnect-app',
    storageBucket: 'my-cleanconnect-app.firebasestorage.app',
    iosBundleId: 'com.example.cleanconnectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTpY9ypjgfVHn0E5_9wiwbOlQwQ2c4Qnk',
    appId: '1:850791330193:web:d6b5cb27fd146a3fefea30',
    messagingSenderId: '850791330193',
    projectId: 'my-cleanconnect-app',
    authDomain: 'my-cleanconnect-app.firebaseapp.com',
    storageBucket: 'my-cleanconnect-app.firebasestorage.app',
  );

}