// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Xkz89qJhKkKUj5mxLOZYa21wJ77IlrM',
    appId: '1:387907876861:web:45a5fde42b39728cd60b94',
    messagingSenderId: '387907876861',
    projectId: 'buz-track-app',
    authDomain: 'buz-track-app.firebaseapp.com',
    storageBucket: 'buz-track-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIWhOAY5Fc4LjNHdJbID5OlcXTf7iLK3g',
    appId: '1:387907876861:android:d5b2225855d26c78d60b94',
    messagingSenderId: '387907876861',
    projectId: 'buz-track-app',
    storageBucket: 'buz-track-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCoqRAcG77iSaBq4mBpYZGXru7DUvI8WI',
    appId: '1:387907876861:ios:a425c7a3b49ca1fad60b94',
    messagingSenderId: '387907876861',
    projectId: 'buz-track-app',
    storageBucket: 'buz-track-app.firebasestorage.app',
    iosBundleId: 'com.example.buztracks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCoqRAcG77iSaBq4mBpYZGXru7DUvI8WI',
    appId: '1:387907876861:ios:a425c7a3b49ca1fad60b94',
    messagingSenderId: '387907876861',
    projectId: 'buz-track-app',
    storageBucket: 'buz-track-app.firebasestorage.app',
    iosBundleId: 'com.example.buztracks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Xkz89qJhKkKUj5mxLOZYa21wJ77IlrM',
    appId: '1:387907876861:web:511d21bc98741549d60b94',
    messagingSenderId: '387907876861',
    projectId: 'buz-track-app',
    authDomain: 'buz-track-app.firebaseapp.com',
    storageBucket: 'buz-track-app.firebasestorage.app',
  );
}
