// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUj6BrqlU--qOqHVURL5AoCS-FiLTeCu0',
    appId: '1:332522480175:web:27a466662f083ee0f45cda',
    messagingSenderId: '332522480175',
    projectId: 'rent-jules-app',
    authDomain: 'rent-jules-app.firebaseapp.com',
    storageBucket: 'rent-jules-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCWZ86zWC6zsYP8MONh8vWhrreCsdLFU',
    appId: '1:332522480175:android:c1233f9caa0b96f9f45cda',
    messagingSenderId: '332522480175',
    projectId: 'rent-jules-app',
    storageBucket: 'rent-jules-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3i3X5erM9pivOLNM1z8YGixzbY4riOQ',
    appId: '1:332522480175:ios:39df407d75bbe331f45cda',
    messagingSenderId: '332522480175',
    projectId: 'rent-jules-app',
    storageBucket: 'rent-jules-app.firebasestorage.app',
    iosBundleId: 'com.example.multicurrencyconverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3i3X5erM9pivOLNM1z8YGixzbY4riOQ',
    appId: '1:332522480175:ios:39df407d75bbe331f45cda',
    messagingSenderId: '332522480175',
    projectId: 'rent-jules-app',
    storageBucket: 'rent-jules-app.firebasestorage.app',
    iosBundleId: 'com.example.multicurrencyconverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUj6BrqlU--qOqHVURL5AoCS-FiLTeCu0',
    appId: '1:332522480175:web:c70964218d2e9d6cf45cda',
    messagingSenderId: '332522480175',
    projectId: 'rent-jules-app',
    authDomain: 'rent-jules-app.firebaseapp.com',
    storageBucket: 'rent-jules-app.firebasestorage.app',
  );
}
