// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtWpluff-bdK6LPPMApvMhBEBxOwON4Q',
    appId: '1:823573373027:web:1411fa408a97de88261856',
    messagingSenderId: '823573373027',
    projectId: 'store-track-app',
    authDomain: 'store-track-app.firebaseapp.com',
    storageBucket: 'store-track-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sVQn5f6fRBzNt4x1yMG3ySoePRzM-hI',
    appId: '1:823573373027:android:01a31683de55f182261856',
    messagingSenderId: '823573373027',
    projectId: 'store-track-app',
    storageBucket: 'store-track-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPHlcYHf45A91s0k-6lVesqoCLiAgaoLA',
    appId: '1:823573373027:ios:b65175d8126d1ccd261856',
    messagingSenderId: '823573373027',
    projectId: 'store-track-app',
    storageBucket: 'store-track-app.firebasestorage.app',
    iosBundleId: 'com.example.storetrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPHlcYHf45A91s0k-6lVesqoCLiAgaoLA',
    appId: '1:823573373027:ios:b65175d8126d1ccd261856',
    messagingSenderId: '823573373027',
    projectId: 'store-track-app',
    storageBucket: 'store-track-app.firebasestorage.app',
    iosBundleId: 'com.example.storetrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHtWpluff-bdK6LPPMApvMhBEBxOwON4Q',
    appId: '1:823573373027:web:fc48edb5ee3e38bb261856',
    messagingSenderId: '823573373027',
    projectId: 'store-track-app',
    authDomain: 'store-track-app.firebaseapp.com',
    storageBucket: 'store-track-app.firebasestorage.app',
  );
}
