// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD49E19NioosjlHbMvTJ2Wn21xBly3QzM0',
    appId: '1:783635631910:web:aaf535ca16cb1f4828fbe7',
    messagingSenderId: '783635631910',
    projectId: 'mobileapp-9db35',
    authDomain: 'mobileapp-9db35.firebaseapp.com',
    storageBucket: 'mobileapp-9db35.firebasestorage.app',
    measurementId: 'G-NR5RXM3G3E',
    databaseURL: 'https://mobileapp-9db35-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnvT4pHQ2nPlnbPunm4oOu1cxBQegSvA',
    appId: '1:783635631910:android:593361d4139ce90128fbe7',
    messagingSenderId: '783635631910',
    projectId: 'mobileapp-9db35',
    storageBucket: 'mobileapp-9db35.firebasestorage.app',
    databaseURL: 'https://mobileapp-9db35-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykPh3SmgZiHwXW18INAtmSfrEPDrUv5U',
    appId: '1:783635631910:ios:a2f3b2b142a33dea28fbe7',
    messagingSenderId: '783635631910',
    projectId: 'mobileapp-9db35',
    storageBucket: 'mobileapp-9db35.firebasestorage.app',
    iosClientId: '783635631910-2lnj031an083o9iutbi180rauunj6itv.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymate',
    databaseURL: 'https://mobileapp-9db35-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykPh3SmgZiHwXW18INAtmSfrEPDrUv5U',
    appId: '1:783635631910:ios:a2f3b2b142a33dea28fbe7',
    messagingSenderId: '783635631910',
    projectId: 'mobileapp-9db35',
    storageBucket: 'mobileapp-9db35.firebasestorage.app',
    iosClientId: '783635631910-2lnj031an083o9iutbi180rauunj6itv.apps.googleusercontent.com',
    iosBundleId: 'com.example.studymate',
    databaseURL: 'https://mobileapp-9db35-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD49E19NioosjlHbMvTJ2Wn21xBly3QzM0',
    appId: '1:783635631910:web:b980b45f5e8725a828fbe7',
    messagingSenderId: '783635631910',
    projectId: 'mobileapp-9db35',
    authDomain: 'mobileapp-9db35.firebaseapp.com',
    storageBucket: 'mobileapp-9db35.firebasestorage.app',
    measurementId: 'G-WS4WNTJFLC',
    databaseURL: 'https://mobileapp-9db35-default-rtdb.firebaseio.com/',
  );
}
