// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-GKj4MsyvMSrXuWv3tB9kKeYsU9uSpwo',
    appId: '1:826550518174:web:00fd9e96519e38ec39968f',
    messagingSenderId: '826550518174',
    projectId: 'tradewear-862ad',
    authDomain: 'tradewear-862ad.firebaseapp.com',
    storageBucket: 'tradewear-862ad.firebasestorage.app',
    measurementId: 'G-DM782X90NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxesfZg-h6IcBxzGWDIyUXGzls1NI89zk',
    appId: '1:826550518174:android:aea3c08e746f019639968f',
    messagingSenderId: '826550518174',
    projectId: 'tradewear-862ad',
    storageBucket: 'tradewear-862ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXevPTwkZgmmem2WrChZClBee9pPSBKjY',
    appId: '1:826550518174:ios:b5685c01216c4e5939968f',
    messagingSenderId: '826550518174',
    projectId: 'tradewear-862ad',
    storageBucket: 'tradewear-862ad.firebasestorage.app',
    iosClientId: '826550518174-rrl3ggdm9h8cnichldm3016r7h7sgreu.apps.googleusercontent.com',
    iosBundleId: 'com.example.henriette',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXevPTwkZgmmem2WrChZClBee9pPSBKjY',
    appId: '1:826550518174:ios:b5685c01216c4e5939968f',
    messagingSenderId: '826550518174',
    projectId: 'tradewear-862ad',
    storageBucket: 'tradewear-862ad.firebasestorage.app',
    iosClientId: '826550518174-rrl3ggdm9h8cnichldm3016r7h7sgreu.apps.googleusercontent.com',
    iosBundleId: 'com.example.henriette',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-GKj4MsyvMSrXuWv3tB9kKeYsU9uSpwo',
    appId: '1:826550518174:web:696568a32459c2a039968f',
    messagingSenderId: '826550518174',
    projectId: 'tradewear-862ad',
    authDomain: 'tradewear-862ad.firebaseapp.com',
    storageBucket: 'tradewear-862ad.firebasestorage.app',
    measurementId: 'G-NPGWGP1SE4',
  );
}
