// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjcd0MVuO9MbafQnqcQEac_7cDBxcQEno',
    appId: '1:67607847313:web:816b1b03538f5ff46bba30',
    messagingSenderId: '67607847313',
    projectId: 'school-messenger-app',
    authDomain: 'school-messenger-app.firebaseapp.com',
    storageBucket: 'school-messenger-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUyf4WexXdzgGpbk1Zbt5BCW53Nfb_3Wk',
    appId: '1:67607847313:android:0b338e811cdd0c386bba30',
    messagingSenderId: '67607847313',
    projectId: 'school-messenger-app',
    storageBucket: 'school-messenger-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFeMIR8VFdEY_AsJcak1G5r19z8XDwnUM',
    appId: '1:67607847313:ios:8f3e582691ce84b66bba30',
    messagingSenderId: '67607847313',
    projectId: 'school-messenger-app',
    storageBucket: 'school-messenger-app.firebasestorage.app',
    iosBundleId: 'com.example.schoolmessenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFeMIR8VFdEY_AsJcak1G5r19z8XDwnUM',
    appId: '1:67607847313:ios:8f3e582691ce84b66bba30',
    messagingSenderId: '67607847313',
    projectId: 'school-messenger-app',
    storageBucket: 'school-messenger-app.firebasestorage.app',
    iosBundleId: 'com.example.schoolmessenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjcd0MVuO9MbafQnqcQEac_7cDBxcQEno',
    appId: '1:67607847313:web:3940b24444f55dbb6bba30',
    messagingSenderId: '67607847313',
    projectId: 'school-messenger-app',
    authDomain: 'school-messenger-app.firebaseapp.com',
    storageBucket: 'school-messenger-app.firebasestorage.app',
  );
}
