// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqT85sAkBKZEGMs-nPMrTgSqcHCc1ohw',
    appId: '1:824983185542:web:562477dcddff9cb5e1c907',
    messagingSenderId: '824983185542',
    projectId: 'fitnessappexam',
    authDomain: 'fitnessappexam.firebaseapp.com',
    storageBucket: 'fitnessappexam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVsnrzJ7eO1mTVJaAAqcFEKACy-Crwo8',
    appId: '1:824983185542:android:6287fb3ad9a3437ae1c907',
    messagingSenderId: '824983185542',
    projectId: 'fitnessappexam',
    storageBucket: 'fitnessappexam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTwgaZ6LtIIvw0cfKfmipFSZSpieyZgE',
    appId: '1:824983185542:ios:0cc43ef529ff6a1be1c907',
    messagingSenderId: '824983185542',
    projectId: 'fitnessappexam',
    storageBucket: 'fitnessappexam.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTwgaZ6LtIIvw0cfKfmipFSZSpieyZgE',
    appId: '1:824983185542:ios:0cc43ef529ff6a1be1c907',
    messagingSenderId: '824983185542',
    projectId: 'fitnessappexam',
    storageBucket: 'fitnessappexam.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFqT85sAkBKZEGMs-nPMrTgSqcHCc1ohw',
    appId: '1:824983185542:web:2863e12a3305c41ae1c907',
    messagingSenderId: '824983185542',
    projectId: 'fitnessappexam',
    authDomain: 'fitnessappexam.firebaseapp.com',
    storageBucket: 'fitnessappexam.firebasestorage.app',
  );
}
