name: cookmate

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_analytics: ^11.5.2
  firebase_storage: ^12.4.9
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5
  google_sign_in: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google-icon.png
    - assets/images/dish.jpg
