// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYYunFvb6hpI6hPXRa4agbY-sR838Daj4',
    appId: '1:982967923233:web:b8c3968d9f738f10742960',
    messagingSenderId: '982967923233',
    projectId: 'quickdocs-7000f',
    authDomain: 'quickdocs-7000f.firebaseapp.com',
    storageBucket: 'quickdocs-7000f.firebasestorage.app',
    measurementId: 'G-H1L7R11GCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc_OH5T-6tLvVOS8prCTcyZNt_28IGVGg',
    appId: '1:982967923233:android:79eb06902020913c742960',
    messagingSenderId: '982967923233',
    projectId: 'quickdocs-7000f',
    storageBucket: 'quickdocs-7000f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6yWoy6pSf5DXXDhY7oKxAm8fsO7veDvE',
    appId: '1:982967923233:ios:066f73746e2bdd62742960',
    messagingSenderId: '982967923233',
    projectId: 'quickdocs-7000f',
    storageBucket: 'quickdocs-7000f.firebasestorage.app',
    iosBundleId: 'com.example.quickdocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6yWoy6pSf5DXXDhY7oKxAm8fsO7veDvE',
    appId: '1:982967923233:ios:066f73746e2bdd62742960',
    messagingSenderId: '982967923233',
    projectId: 'quickdocs-7000f',
    storageBucket: 'quickdocs-7000f.firebasestorage.app',
    iosBundleId: 'com.example.quickdocs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYYunFvb6hpI6hPXRa4agbY-sR838Daj4',
    appId: '1:982967923233:web:f9b6cf0d7d0f5880742960',
    messagingSenderId: '982967923233',
    projectId: 'quickdocs-7000f',
    authDomain: 'quickdocs-7000f.firebaseapp.com',
    storageBucket: 'quickdocs-7000f.firebasestorage.app',
    measurementId: 'G-9MP3BM6331',
  );

}