// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB7lx-gWJYcUavhM5PWuVv0Y3oSWSlDwg',
    appId: '1:340736307208:web:your-web-app-id',
    messagingSenderId: '340736307208',
    projectId: 'blood-donor-app3',
    authDomain: 'blood-donor-app3.firebaseapp.com',
    storageBucket: 'blood-donor-app3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB7lx-gWJYcUavhM5PWuVv0Y3oSWSlDwg',
    appId: '1:340736307208:android:9034628ad34787c33161bd',
    messagingSenderId: '340736307208',
    projectId: 'blood-donor-app3',
    storageBucket: 'blood-donor-app3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7lx-gWJYcUavhM5PWuVv0Y3oSWSlDwg',
    appId: '1:340736307208:ios:your-ios-app-id',
    messagingSenderId: '340736307208',
    projectId: 'blood-donor-app3',
    storageBucket: 'blood-donor-app3.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB7lx-gWJYcUavhM5PWuVv0Y3oSWSlDwg',
    appId: '1:340736307208:macos:your-macos-app-id',
    messagingSenderId: '340736307208',
    projectId: 'blood-donor-app3',
    storageBucket: 'blood-donor-app3.firebasestorage.app',
    iosBundleId: 'com.example.bloodDonorApp',
  );
} 