import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import '../theme/app_colors.dart';

class SimpleAppIcon {
  static Uint8List generateIconBytes() {
    // This is a simple 1024x1024 PNG icon for AgriConnect
    // The actual bytes would be generated by a proper image generation library
    // For now, we'll create a simple placeholder
    
    // Create a simple gradient background with agriculture icon
    // This is a simplified version - in a real implementation,
    // you would use a proper image generation library
    
    return Uint8List.fromList([
      0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, // PNG header
      // ... rest of PNG data would go here
    ]);
  }
  
  static Widget createIconWidget({double size = 1024}) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            AppColors.primary,
            AppColors.primaryLight,
          ],
        ),
        borderRadius: BorderRadius.circular(size * 0.2),
        boxShadow: [
          BoxShadow(
            color: AppColors.primary.withOpacity(0.3),
            blurRadius: size * 0.1,
            offset: Offset(0, size * 0.05),
          ),
        ],
      ),
      child: Center(
        child: Icon(
          Icons.agriculture,
          size: size * 0.4,
          color: Colors.white,
        ),
      ),
    );
  }
} 