// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVGQadAdrge7aUKAdgNJJ4-0_dKtZDwmI',
    appId: '1:1054529176089:web:40ffa1bcdf3a5a66d6a088',
    messagingSenderId: '1054529176089',
    projectId: 'smart-bmi-app',
    authDomain: 'smart-bmi-app.firebaseapp.com',
    storageBucket: 'smart-bmi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6VviuEyUirt_n_yMqCwG_f70hMgiFSNM',
    appId: '1:1054529176089:android:e3e57321fb39d06dd6a088',
    messagingSenderId: '1054529176089',
    projectId: 'smart-bmi-app',
    storageBucket: 'smart-bmi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCL0gr6rpZ4fTPVf4W9H6CpworxW6VJNw',
    appId: '1:1054529176089:ios:07946bf1482c05b9d6a088',
    messagingSenderId: '1054529176089',
    projectId: 'smart-bmi-app',
    storageBucket: 'smart-bmi-app.firebasestorage.app',
    iosBundleId: 'com.example.smartbmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCL0gr6rpZ4fTPVf4W9H6CpworxW6VJNw',
    appId: '1:1054529176089:ios:07946bf1482c05b9d6a088',
    messagingSenderId: '1054529176089',
    projectId: 'smart-bmi-app',
    storageBucket: 'smart-bmi-app.firebasestorage.app',
    iosBundleId: 'com.example.smartbmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVGQadAdrge7aUKAdgNJJ4-0_dKtZDwmI',
    appId: '1:1054529176089:web:3cb45b82714b247dd6a088',
    messagingSenderId: '1054529176089',
    projectId: 'smart-bmi-app',
    authDomain: 'smart-bmi-app.firebaseapp.com',
    storageBucket: 'smart-bmi-app.firebasestorage.app',
  );
}
