// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-KrXGvUqGSNhBjkTi4TB1MwqUEg7BxI',
    appId: '1:891812320686:web:79a8c3b5c5d3b51b8a243f',
    messagingSenderId: '891812320686',
    projectId: 'internlink-app-db',
    authDomain: 'internlink-app-db.firebaseapp.com',
    storageBucket: 'internlink-app-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwPA4v2xPnwxZzpVh9wwsUROosk4ZkJQ',
    appId: '1:891812320686:android:31613d15aa2552578a243f',
    messagingSenderId: '891812320686',
    projectId: 'internlink-app-db',
    storageBucket: 'internlink-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxF0GOmIlbh0sgvgJ_DB2FxLelPo7P2GI',
    appId: '1:891812320686:ios:796343070a28675a8a243f',
    messagingSenderId: '891812320686',
    projectId: 'internlink-app-db',
    storageBucket: 'internlink-app-db.firebasestorage.app',
    iosBundleId: 'com.example.internlinkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxF0GOmIlbh0sgvgJ_DB2FxLelPo7P2GI',
    appId: '1:891812320686:ios:796343070a28675a8a243f',
    messagingSenderId: '891812320686',
    projectId: 'internlink-app-db',
    storageBucket: 'internlink-app-db.firebasestorage.app',
    iosBundleId: 'com.example.internlinkapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-KrXGvUqGSNhBjkTi4TB1MwqUEg7BxI',
    appId: '1:891812320686:web:3a3e11da5e7dde508a243f',
    messagingSenderId: '891812320686',
    projectId: 'internlink-app-db',
    authDomain: 'internlink-app-db.firebaseapp.com',
    storageBucket: 'internlink-app-db.firebasestorage.app',
  );
}
