name: bet_nova
version: 1.0.0+1
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_messaging: ^15.2.7
  flutterfire_cli: ^1.3.1
  intl: ^0.18.1
  provider: ^6.0.5
  badges: ^3.1.2
  url_launcher: ^6.2.6
  flutter_svg: ^2.0.10
  carousel_slider: ^5.1.1
  image_picker: ^1.0.4
  firebase_storage: ^12.4.7
  firebase_analytics: ^11.5.2
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_screen/splash.png
  android: true
  ios: true
  web: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/full_international_football_champions.json
    - assets/international_basketball_champions.json
    - assets/international_volleyball_champions.json
    - assets/icon/
    - assets/splash_screen/
