// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tRh81AFJrjn5YQACh7EN6owMlFbebD4',
    appId: '1:416201369699:web:e18181a5a1a9d349c07056',
    messagingSenderId: '416201369699',
    projectId: 'farmerpay-f81b7',
    authDomain: 'farmerpay-f81b7.firebaseapp.com',
    storageBucket: 'farmerpay-f81b7.firebasestorage.app',
    measurementId: 'G-JHHXYL25Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSeLGqGlZrj8_1u6OPTQJXanJmKUNiHho',
    appId: '1:416201369699:android:c42b2eebab692b93c07056',
    messagingSenderId: '416201369699',
    projectId: 'farmerpay-f81b7',
    storageBucket: 'farmerpay-f81b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvvMb1hVzUv6n5vjhpzEkUNkkhG5RqXzA',
    appId: '1:416201369699:ios:010a2e7e9701af4ec07056',
    messagingSenderId: '416201369699',
    projectId: 'farmerpay-f81b7',
    storageBucket: 'farmerpay-f81b7.firebasestorage.app',
    iosBundleId: 'com.example.farmpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvvMb1hVzUv6n5vjhpzEkUNkkhG5RqXzA',
    appId: '1:416201369699:ios:010a2e7e9701af4ec07056',
    messagingSenderId: '416201369699',
    projectId: 'farmerpay-f81b7',
    storageBucket: 'farmerpay-f81b7.firebasestorage.app',
    iosBundleId: 'com.example.farmpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3tRh81AFJrjn5YQACh7EN6owMlFbebD4',
    appId: '1:416201369699:web:8f4f62cdd6441975c07056',
    messagingSenderId: '416201369699',
    projectId: 'farmerpay-f81b7',
    authDomain: 'farmerpay-f81b7.firebaseapp.com',
    storageBucket: 'farmerpay-f81b7.firebasestorage.app',
    measurementId: 'G-5EN2BMYFXE',
  );
}
