// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfNb5M7Skw6xH-Vcmwv_CtsOTVsHtORgI',
    appId: '1:999217448261:web:db0d3baecc391d99a6aa2c',
    messagingSenderId: '999217448261',
    projectId: 'skillhire-1e104',
    authDomain: 'skillhire-1e104.firebaseapp.com',
    storageBucket: 'skillhire-1e104.firebasestorage.app',
    measurementId: 'G-KZ15BMDQYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtQqDeQvneGifQRopbY7owbOX_L0cyoNE',
    appId: '1:999217448261:android:37ad76cd430900f2a6aa2c',
    messagingSenderId: '999217448261',
    projectId: 'skillhire-1e104',
    storageBucket: 'skillhire-1e104.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxAyXYmwts4XlpnN_PJykW9UNfxbAbes',
    appId: '1:999217448261:ios:5a4fbfbbf13c5113a6aa2c',
    messagingSenderId: '999217448261',
    projectId: 'skillhire-1e104',
    storageBucket: 'skillhire-1e104.firebasestorage.app',
    iosClientId: '999217448261-mqg7ohqm9tabs6iunvdq41hr85628bud.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillhireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzxAyXYmwts4XlpnN_PJykW9UNfxbAbes',
    appId: '1:999217448261:ios:5a4fbfbbf13c5113a6aa2c',
    messagingSenderId: '999217448261',
    projectId: 'skillhire-1e104',
    storageBucket: 'skillhire-1e104.firebasestorage.app',
    iosClientId: '999217448261-mqg7ohqm9tabs6iunvdq41hr85628bud.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillhireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfNb5M7Skw6xH-Vcmwv_CtsOTVsHtORgI',
    appId: '1:999217448261:web:f3905de4f951fe0fa6aa2c',
    messagingSenderId: '999217448261',
    projectId: 'skillhire-1e104',
    authDomain: 'skillhire-1e104.firebaseapp.com',
    storageBucket: 'skillhire-1e104.firebasestorage.app',
    measurementId: 'G-KJ7T3BFZ23',
  );
}
