// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-edjW5GnkOZU60Uylfy_Hn3gC05bpq8A',
    appId: '1:962570414742:web:7b759603454c67ae19f0b7',
    messagingSenderId: '962570414742',
    projectId: 'rentmate-33596',
    authDomain: 'rentmate-33596.firebaseapp.com',
    storageBucket: 'rentmate-33596.firebasestorage.app',
    measurementId: 'G-K75Q7EQ8C0',
  );

  // Replace these with your actual Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmgu3ApckFswjhQ-MJ5r7myMQtoDWBtV0',
    appId: '1:962570414742:android:2ce27f1a1781a24719f0b7',
    messagingSenderId: '962570414742',
    projectId: 'rentmate-33596',
    storageBucket: 'rentmate-33596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1V5BoYc5N00oi7Q__R4i0Gy_RUagLic',
    appId: '1:962570414742:ios:27db702a5005fcd019f0b7',
    messagingSenderId: '962570414742',
    projectId: 'rentmate-33596',
    storageBucket: 'rentmate-33596.firebasestorage.app',
    iosBundleId: 'com.example.mobileExam22rp03693',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1V5BoYc5N00oi7Q__R4i0Gy_RUagLic',
    appId: '1:962570414742:ios:27db702a5005fcd019f0b7',
    messagingSenderId: '962570414742',
    projectId: 'rentmate-33596',
    storageBucket: 'rentmate-33596.firebasestorage.app',
    iosBundleId: 'com.example.mobileExam22rp03693',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-edjW5GnkOZU60Uylfy_Hn3gC05bpq8A',
    appId: '1:962570414742:web:65cb7b17da153bd019f0b7',
    messagingSenderId: '962570414742',
    projectId: 'rentmate-33596',
    authDomain: 'rentmate-33596.firebaseapp.com',
    storageBucket: 'rentmate-33596.firebasestorage.app',
    measurementId: 'G-SYM6X5CE6M',
  );

}