// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA01QFOst9BIz0uxC-rTWQMDri8MMMfKe8',
    appId: '1:813510701971:web:a96177b94dd202ea8dae66',
    messagingSenderId: '813510701971',
    projectId: 'exam-choice-app',
    authDomain: 'exam-choice-app.firebaseapp.com',
    storageBucket: 'exam-choice-app.firebasestorage.app',
    measurementId: 'G-M7YCL6ZJVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBACYvZTlQbLhyh8W6X0JGj07tqA1oc4dU',
    appId: '1:813510701971:android:0d4d42405504a7f18dae66',
    messagingSenderId: '813510701971',
    projectId: 'exam-choice-app',
    storageBucket: 'exam-choice-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkxhosnyVx-5yGmEx46Xw0zUJn7WwmRAI',
    appId: '1:813510701971:ios:f7548d34fc6acf378dae66',
    messagingSenderId: '813510701971',
    projectId: 'exam-choice-app',
    storageBucket: 'exam-choice-app.firebasestorage.app',
    iosBundleId: 'com.example.examapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkxhosnyVx-5yGmEx46Xw0zUJn7WwmRAI',
    appId: '1:813510701971:ios:f7548d34fc6acf378dae66',
    messagingSenderId: '813510701971',
    projectId: 'exam-choice-app',
    storageBucket: 'exam-choice-app.firebasestorage.app',
    iosBundleId: 'com.example.examapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA01QFOst9BIz0uxC-rTWQMDri8MMMfKe8',
    appId: '1:813510701971:web:2b686271cb103d518dae66',
    messagingSenderId: '813510701971',
    projectId: 'exam-choice-app',
    authDomain: 'exam-choice-app.firebaseapp.com',
    storageBucket: 'exam-choice-app.firebasestorage.app',
    measurementId: 'G-BEHK35ND4J',
  );
}
