final List<Map<String, dynamic>> questionsData = [

  // 🌍 GEOGRAPHY
  {
    'question': 'What is the capital city of Australia?',
'options': ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
'answer': 'Canberra',
'explanation': 'Canberra is the capital city of Australia.',
'category': 'geography',
},
{
    'question': 'Which river is the longest in the world?',
    'options': ['Amazon', 'Nile', 'Yangtze', 'Mississippi'],
    'answer': 'Nile',
    'explanation': 'The Nile is considered the longest river in the world.',
    'category': 'geography',
  },
  {
    'question': 'Which continent has the most countries?',
    'options': ['Asia', 'Europe', 'Africa', 'South America'],
    'answer': 'Africa',
    'explanation': 'Africa has 54 recognized countries, the most of any continent.',
'category': 'geography',
},
{
'question': 'Mount Everest is located in which mountain range?',
    'options': ['Andes', 'Alps', 'Himalayas', 'Rockies'],
'answer': 'Himalayas',
'explanation': 'Mount Everest is part of the Himalayas.',
'category': 'geography',
},
{
    'question': 'Which ocean is the largest?',
    'options': ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    'answer': 'Pacific',
    'explanation': 'The Pacific Ocean is the largest by area.',
'category': 'geography',
},
{
'question': 'What is the smallest country in the world?',
    'options': ['Monaco', 'Malta', 'Vatican City', 'San Marino'],
'answer': 'Vatican City',
    'explanation': 'Vatican City is the smallest by area and population.',
'category': 'geography',
},
{
    'question': 'Which country is known as the Land of the Rising Sun?',
    'options': ['China', 'South Korea', 'Thailand', 'Japan'],
    'answer': 'Japan',
    'explanation': 'Japan is nicknamed the Land of the Rising Sun.',
'category': 'geography',
},
{
    'question': 'What desert is the largest in the world?',
    'options': ['Gobi', 'Sahara', 'Kalahari', 'Antarctica'],
    'answer': 'Antarctica',
    'explanation': 'Antarctica is the largest desert by area.',
'category': 'geography',
},
{
    'question': 'Which US state has the most volcanoes?',
    'options': ['California', 'Alaska', 'Hawaii', 'Washington'],
    'answer': 'Alaska',
    'explanation': 'Alaska has the highest number of volcanoes.',
'category': 'geography',
},
{
    'question': 'Which country has the longest coastline?',
    'options': ['USA', 'Russia', 'Canada', 'Australia'],
    'answer': 'Canada',
    'explanation': 'Canada has the longest coastline in the world.',
'category': 'geography',
},

  // 🔬 SCIENCE
  {
    'question': 'What gas do plants absorb from the atmosphere?',
    'options': ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
    'answer': 'Carbon dioxide',
    'explanation': 'Plants absorb carbon dioxide for photosynthesis.',
    'category': 'science',
  },
  {
    'question': 'What is the boiling point of water at sea level?',
    'options': ['90°C', '100°C', '80°C', '120°C'],
    'answer': '100°C',
    'explanation': 'Water boils at 100°C at sea level.',
    'category': 'science',
  },
  {
    'question': 'What part of the cell contains DNA?',
    'options': ['Nucleus', 'Cytoplasm', 'Ribosome', 'Mitochondria'],
    'answer': 'Nucleus',
    'explanation': 'DNA is stored in the nucleus.',
    'category': 'science',
  },
  {
    'question': 'What is the chemical symbol for gold?',
    'options': ['G', 'Au', 'Ag', 'Go'],
    'answer': 'Au',
    'explanation': 'The symbol for gold is Au.',
    'category': 'science',
  },
  {
    'question': 'Which planet is known as the Red Planet?',
    'options': ['Mars', 'Venus', 'Saturn', 'Mercury'],
    'answer': 'Mars',
    'explanation': 'Mars is often called the Red Planet due to its surface color.',
    'category': 'science',
  },
  {
    'question': 'How many bones are in the adult human body?',
    'options': ['206', '201', '210', '190'],
    'answer': '206',
    'explanation': 'An adult human body has 206 bones.',
    'category': 'science',
  },
  {
    'question': 'What is the main gas found in the air we breathe?',
    'options': ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'],
    'answer': 'Nitrogen',
    'explanation': 'Nitrogen makes up about 78% of the air.',
    'category': 'science',
  },
  {
    'question': 'Which part of the plant makes food?',
    'options': ['Root', 'Stem', 'Leaf', 'Flower'],
    'answer': 'Leaf',
    'explanation': 'Leaves carry out photosynthesis.',
    'category': 'science',
  },
  {
    'question': 'Which organ pumps blood around the body?',
    'options': ['Lung', 'Kidney', 'Heart', 'Liver'],
    'answer': 'Heart',
    'explanation': 'The heart circulates blood through the body.',
    'category': 'science',
  },
  {
    'question': 'Which planet is closest to the sun?',
    'options': ['Venus', 'Earth', 'Mercury', 'Mars'],
    'answer': 'Mercury',
    'explanation': 'Mercury is the closest planet to the sun.',
    'category': 'science',
  },

  // ➗ MATH
  {
    'question': 'What is 12 x 8?',
    'options': ['96', '88', '108', '84'],
    'answer': '96',
    'explanation': '12 multiplied by 8 equals 96.',
    'category': 'mathematics',
},
{
'question': 'What is the square root of 144?',
'options': ['10', '11', '12', '13'],
'answer': '12',
'explanation': 'The square root of 144 is 12.',
    'category': 'mathematics',
  },
  {
    'question': 'What is the value of π (pi) approximately?',
    'options': ['3.14', '2.17', '1.41', '4.22'],
    'answer': '3.14',
    'explanation': 'Pi is approximately 3.14.',
    'category': 'mathematics',
},
{
'question': 'What is 15% of 200?',
    'options': ['20', '25', '30', '35'],
'answer': '30',
'explanation': '15% of 200 is 30.',
    'category': 'mathematics',
  },
  {
    'question': 'What is the next prime number after 7?',
    'options': ['9', '11', '13', '17'],
    'answer': '11',
    'explanation': '11 is the next prime number after 7.',
    'category': 'mathematics',
  },
  {
    'question': 'What is 2 to the power of 5?',
    'options': ['10', '32', '16', '8'],
    'answer': '32',
    'explanation': '2^5 = 32.',
    'category': 'mathematics',
  },
  {
    'question': 'Which shape has 6 sides?',
    'options': ['Square', 'Hexagon', 'Pentagon', 'Octagon'],
    'answer': 'Hexagon',
    'explanation': 'A hexagon has 6 sides.',
    'category': 'mathematics',
  },
  {
    'question': 'What is 100 divided by 4?',
    'options': ['25', '30', '20', '24'],
'answer': '25',
    'explanation': '100 ÷ 4 = 25.',
    'category': 'mathematics',
  },
  {
    'question': 'What is the perimeter of a square with side 5?',
    'options': ['20', '25', '15', '10'],
    'answer': '20',
    'explanation': 'Perimeter = 4 × side = 4 × 5 = 20.',
    'category': 'mathematics',
  },
  {
    'question': 'What is 7 squared?',
    'options': ['42', '49', '56', '64'],
    'answer': '49',
    'explanation': '7 × 7 = 49.',
    'category': 'mathematics',
  },

// ... (To keep response readable, would you like the other 5 categories now?)

  // 🏛 HISTORY
  {
    'question': 'Who was the first President of the United States?',
    'options': ['Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams'],
    'answer': 'George Washington',
    'explanation': 'George Washington was the first U.S. President.',
    'category': 'history',
  },
  {
    'question': 'Which war ended in 1945?',
    'options': ['World War I', 'World War II', 'Korean War', 'Vietnam War'],
    'answer': 'World War II',
    'explanation': 'World War II ended in 1945.',
    'category': 'history',
  },
  {
    'question': 'Who discovered America in 1492?',
    'options': ['Vasco da Gama', 'Christopher Columbus', 'Marco Polo', 'Ferdinand Magellan'],
    'answer': 'Christopher Columbus',
    'explanation': 'Columbus reached the Americas in 1492.',
    'category': 'history',
  },
  {
    'question': 'The Great Wall is located in which country?',
    'options': ['Japan', 'India', 'China', 'Korea'],
    'answer': 'China',
    'explanation': 'The Great Wall is in China.',
    'category': 'history',
  },
  {
    'question': 'Who was known as the Iron Lady?',
    'options': ['Angela Merkel', 'Margaret Thatcher', 'Indira Gandhi', 'Golda Meir'],
    'answer': 'Margaret Thatcher',
    'explanation': 'Thatcher was called the Iron Lady.',
    'category': 'history',
  },
  {
    'question': 'In which year did Rwanda gain independence?',
    'options': ['1959', '1960', '1962', '1965'],
    'answer': '1962',
    'explanation': 'Rwanda gained independence in 1962.',
    'category': 'history',
  },
  {
    'question': 'Who led the Indian independence movement with non-violence?',
    'options': ['Jawaharlal Nehru', 'Subhas Chandra Bose', 'Mahatma Gandhi', 'Rajendra Prasad'],
    'answer': 'Mahatma Gandhi',
    'explanation': 'Gandhi promoted non-violent resistance.',
    'category': 'history',
  },
  {
    'question': 'Where was Nelson Mandela imprisoned?',
    'options': ['Robben Island', 'Cape Town', 'Johannesburg', 'Durban'],
    'answer': 'Robben Island',
    'explanation': 'Mandela was imprisoned on Robben Island.',
    'category': 'history',
  },
  {
    'question': 'Who was the famous female pilot lost at sea?',
    'options': ['Amelia Earhart', 'Harriet Quimby', 'Valentina Tereshkova', 'Bessie Coleman'],
    'answer': 'Amelia Earhart',
    'explanation': 'Earhart disappeared over the Pacific.',
    'category': 'history',
  },
  {
    'question': 'The Berlin Wall fell in which year?',
    'options': ['1987', '1988', '1989', '1990'],
    'answer': '1989',
    'explanation': 'The Berlin Wall fell in 1989.',
    'category': 'history',
  },

  // 💻 TECHNOLOGY
  {
    'question': 'Who is the founder of Microsoft?',
    'options': ['Steve Jobs', 'Bill Gates', 'Elon Musk', 'Larry Page'],
    'answer': 'Bill Gates',
    'explanation': 'Bill Gates co-founded Microsoft.',
    'category': 'technology',
  },
  {
    'question': 'What does CPU stand for?',
    'options': ['Central Power Unit', 'Central Processing Unit', 'Computer Personal Unit', 'Core Processing Unit'],
    'answer': 'Central Processing Unit',
    'explanation': 'CPU stands for Central Processing Unit.',
    'category': 'technology',
  },
  {
    'question': 'Which company makes the iPhone?',
    'options': ['Google', 'Samsung', 'Apple', 'Microsoft'],
    'answer': 'Apple',
    'explanation': 'Apple makes the iPhone.',
    'category': 'technology',
  },
  {
    'question': 'What is the main language used for web pages?',
    'options': ['Java', 'HTML', 'Python', 'C++'],
    'answer': 'HTML',
    'explanation': 'HTML is used for creating web pages.',
    'category': 'technology',
  },
  {
    'question': 'Which of the following is a search engine?',
    'options': ['Firefox', 'Google', 'Safari', 'Windows'],
    'answer': 'Google',
    'explanation': 'Google is a popular search engine.',
    'category': 'technology',
  },
  {
    'question': 'What does "Wi-Fi" allow devices to do?',
    'options': ['Print', 'Connect to the internet', 'Store files', 'Charge'],
    'answer': 'Connect to the internet',
    'explanation': 'Wi-Fi enables internet connectivity.',
    'category': 'technology',
  },
  {
    'question': 'What is the name of Facebook’s parent company?',
    'options': ['Meta', 'Alphabet', 'ByteDance', 'X'],
    'answer': 'Meta',
    'explanation': 'Facebook rebranded to Meta.',
    'category': 'technology',
  },
  {
    'question': 'What device is used to input text?',
    'options': ['Monitor', 'Keyboard', 'Mouse', 'Speaker'],
    'answer': 'Keyboard',
    'explanation': 'A keyboard is used for text input.',
    'category': 'technology',
  },
  {
    'question': 'Which programming language is used in Flutter?',
    'options': ['Java', 'Kotlin', 'Dart', 'Swift'],
    'answer': 'Dart',
    'explanation': 'Flutter uses Dart for development.',
    'category': 'technology',
  },
  {
    'question': 'What is used to store data permanently?',
    'options': ['RAM', 'Cache', 'SSD', 'Processor'],
    'answer': 'SSD',
    'explanation': 'SSD is a type of permanent storage.',
    'category': 'technology',
  },

  // 🏀 SPORTS
  {
    'question': 'How many players are on a soccer team on the field?',
    'options': ['9', '10', '11', '12'],
'answer': '11',
    'explanation': 'Each soccer team has 11 players.',
    'category': 'sports',
  },
  {
    'question': 'Which country has won the most FIFA World Cups?',
    'options': ['Germany', 'Italy', 'Argentina', 'Brazil'],
    'answer': 'Brazil',
    'explanation': 'Brazil has won 5 World Cups.',
    'category': 'sports',
  },
  {
    'question': 'What sport does Serena Williams play?',
    'options': ['Basketball', 'Tennis', 'Golf', 'Volleyball'],
    'answer': 'Tennis',
    'explanation': 'Serena Williams is a tennis player.',
    'category': 'sports',
  },
  {
    'question': 'How many rings are on the Olympic flag?',
    'options': ['4', '5', '6', '7'],
    'answer': '5',
    'explanation': 'The Olympic flag has 5 rings.',
    'category': 'sports',
  },
  {
    'question': 'Which sport is known as the "king of sports"?',
    'options': ['Basketball', 'Tennis', 'Soccer', 'Baseball'],
    'answer': 'Soccer',
    'explanation': 'Soccer is the world’s most popular sport.',
    'category': 'sports',
  },
  {
    'question': 'In which sport is the term "home run" used?',
    'options': ['Basketball', 'Baseball', 'Cricket', 'Hockey'],
    'answer': 'Baseball',
    'explanation': 'Home run is a term in baseball.',
    'category': 'sports',
  },
  {
    'question': 'What country hosts the Wimbledon tournament?',
    'options': ['USA', 'France', 'UK', 'Australia'],
    'answer': 'UK',
    'explanation': 'Wimbledon is held in London, UK.',
    'category': 'sports',
  },
  {
    'question': 'Which athlete has won the most Olympic medals?',
    'options': ['Usain Bolt', 'Michael Phelps', 'Simone Biles', 'Carl Lewis'],
    'answer': 'Michael Phelps',
    'explanation': 'Phelps has the most Olympic medals.',
    'category': 'sports',
  },
  {
    'question': 'What sport uses a puck?',
    'options': ['Cricket', 'Hockey', 'Baseball', 'Rugby'],
    'answer': 'Hockey',
    'explanation': 'A puck is used in hockey.',
    'category': 'sports',
  },
  {
    'question': 'How long is a standard football match?',
    'options': ['90 minutes', '80 minutes', '70 minutes', '100 minutes'],
    'answer': '90 minutes',
    'explanation': 'A football match lasts 90 minutes.',
    'category': 'sports',
  },

  // 📖 LITERATURE
  {
    'question': 'Who wrote "Romeo and Juliet"?',
    'options': ['William Shakespeare', 'Charles Dickens', 'Jane Austen', 'J.K. Rowling'],
    'answer': 'William Shakespeare',
    'explanation': 'Shakespeare wrote Romeo and Juliet.',
    'category': 'literature',
  },
  {
    'question': 'What is the name of Harry Potter’s school?',
    'options': ['Beauxbatons', 'Durmstrang', 'Hogwarts', 'Ilvermorny'],
    'answer': 'Hogwarts',
    'explanation': 'Harry Potter studied at Hogwarts.',
    'category': 'literature',
  },
  {
    'question': 'Who wrote "Animal Farm"?',
    'options': ['George Orwell', 'Ernest Hemingway', 'Leo Tolstoy', 'Mark Twain'],
    'answer': 'George Orwell',
    'explanation': 'Animal Farm was written by George Orwell.',
    'category': 'literature',
  },
  {
    'question': 'What genre is Sherlock Holmes?',
    'options': ['Fantasy', 'Romance', 'Detective', 'Sci-fi'],
    'answer': 'Detective',
    'explanation': 'Sherlock Holmes is a detective series.',
    'category': 'literature',
  },
  {
    'question': 'Who wrote "Pride and Prejudice"?',
    'options': ['Emily Brontë', 'Jane Austen', 'Virginia Woolf', 'Louisa May Alcott'],
    'answer': 'Jane Austen',
    'explanation': 'Jane Austen wrote Pride and Prejudice.',
    'category': 'literature',
  },
  {
    'question': 'What is the main language of "The Alchemist" originally?',
    'options': ['Spanish', 'French', 'Portuguese', 'English'],
    'answer': 'Portuguese',
    'explanation': 'The Alchemist was originally written in Portuguese.',
    'category': 'literature',
  },
  {
    'question': 'Which author created Narnia?',
    'options': ['C.S. Lewis', 'J.R.R. Tolkien', 'Roald Dahl', 'Dr. Seuss'],
    'answer': 'C.S. Lewis',
    'explanation': 'The Chronicles of Narnia is by C.S. Lewis.',
    'category': 'literature',
  },
  {
    'question': 'Who wrote "The Hobbit"?',
    'options': ['C.S. Lewis', 'George R.R. Martin', 'J.K. Rowling', 'J.R.R. Tolkien'],
    'answer': 'J.R.R. Tolkien',
    'explanation': 'Tolkien wrote The Hobbit.',
    'category': 'literature',
  },
  {
    'question': 'Which novel begins with “Call me Ishmael”?',
    'options': ['Moby Dick', 'The Odyssey', 'Dracula', 'Frankenstein'],
    'answer': 'Moby Dick',
    'explanation': '“Call me Ishmael” is the first line of Moby Dick.',
    'category': 'literature',
  },
  {
    'question': 'Who is the author of "Things Fall Apart"?',
    'options': ['Chinua Achebe', 'Ngugi wa Thiong’o', 'Wole Soyinka', 'Ben Okri'],
    'answer': 'Chinua Achebe',
    'explanation': 'Things Fall Apart was written by Chinua Achebe.',
    'category': 'literature',
  },

  // 🌐 GENERAL KNOWLEDGE
  {
    'question': 'How many continents are there in the world?',
'options': ['5', '6', '7', '8'],
    'answer': '7',
    'explanation': 'There are 7 continents on Earth.',
    'category': 'general knowledge',
  },
  {
    'question': 'Which currency is used in Japan?',
    'options': ['Won', 'Yuan', 'Dollar', 'Yen'],
    'answer': 'Yen',
    'explanation': 'Japan uses the Yen.',
    'category': 'general knowledge',
  },
  {
    'question': 'Which day is celebrated as New Year?',
    'options': ['December 25', 'January 1', 'July 4', 'March 21'],
    'answer': 'January 1',
    'explanation': 'New Year is on January 1st.',
    'category': 'general knowledge',
  },
  {
    'question': 'Which is the tallest animal on Earth?',
    'options': ['Elephant', 'Horse', 'Giraffe', 'Kangaroo'],
    'answer': 'Giraffe',
    'explanation': 'Giraffes are the tallest land animals.',
    'category': 'general knowledge',
  },
  {
    'question': 'What is the human body’s largest organ?',
    'options': ['Heart', 'Liver', 'Skin', 'Brain'],
    'answer': 'Skin',
    'explanation': 'The skin is the body’s largest organ.',
    'category': 'general knowledge',
  },
  {
    'question': 'What is the main ingredient in bread?',
    'options': ['Salt', 'Water', 'Sugar', 'Flour'],
    'answer': 'Flour',
    'explanation': 'Bread is made mainly from flour.',
    'category': 'general knowledge',
  },
  {
    'question': 'How many hours are in a day?',
    'options': ['12', '24', '48', '60'],
    'answer': '24',
    'explanation': 'There are 24 hours in a day.',
    'category': 'general knowledge',
  },
  {
    'question': 'Which animal is known as man’s best friend?',
    'options': ['Cat', 'Horse', 'Dog', 'Elephant'],
    'answer': 'Dog',
    'explanation': 'Dogs are often called man’s best friend.',
    'category': 'general knowledge',
  },
  {
    'question': 'What is used to write on a blackboard?',
    'options': ['Pen', 'Pencil', 'Chalk', 'Marker'],
    'answer': 'Chalk',
    'explanation': 'Chalk is used on blackboards.',
    'category': 'general knowledge',
  },
  {
    'question': 'Which month has 28 days?',
    'options': ['February', 'April', 'June', 'September'],
    'answer': 'February',
    'explanation': 'February has 28 or 29 days.',
    'category': 'general knowledge',
  },

];
