// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVzhx4nmVfGSWk09n440ZxcU_CetV5GEk',
    appId: '1:471589742918:web:a3b00165bb14d413531d47',
    messagingSenderId: '471589742918',
    projectId: 'smartbudget-74b65',
    authDomain: 'smartbudget-74b65.firebaseapp.com',
    storageBucket: 'smartbudget-74b65.firebasestorage.app',
    measurementId: 'G-LSRL7Z9YR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZLq4vKpCi3Rwkw-wCZMlfxjo3rBdYo4s',
    appId: '1:471589742918:android:fe5fd02cf32a130e531d47',
    messagingSenderId: '471589742918',
    projectId: 'smartbudget-74b65',
    storageBucket: 'smartbudget-74b65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZ2E_8LN_-2mjbR84IeNmotNEDRnlvBw',
    appId: '1:471589742918:ios:6b1b0d0666394c49531d47',
    messagingSenderId: '471589742918',
    projectId: 'smartbudget-74b65',
    storageBucket: 'smartbudget-74b65.firebasestorage.app',
    iosBundleId: 'com.example.smartbudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNZ2E_8LN_-2mjbR84IeNmotNEDRnlvBw',
    appId: '1:471589742918:ios:6b1b0d0666394c49531d47',
    messagingSenderId: '471589742918',
    projectId: 'smartbudget-74b65',
    storageBucket: 'smartbudget-74b65.firebasestorage.app',
    iosBundleId: 'com.example.smartbudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVzhx4nmVfGSWk09n440ZxcU_CetV5GEk',
    appId: '1:471589742918:web:2e7469535dba2464531d47',
    messagingSenderId: '471589742918',
    projectId: 'smartbudget-74b65',
    authDomain: 'smartbudget-74b65.firebaseapp.com',
    storageBucket: 'smartbudget-74b65.firebasestorage.app',
    measurementId: 'G-QPKFM875J6',
  );
}
