// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNZkqMWvHNM5zJcuV5mjlBtFx0hLtUec',
    appId: '1:752140122484:web:373caaacf90c9a1fc3d421',
    messagingSenderId: '752140122484',
    projectId: 'cookmate-4831f',
    authDomain: 'cookmate-4831f.firebaseapp.com',
    storageBucket: 'cookmate-4831f.firebasestorage.app',
    measurementId: 'G-40SYNQ4PHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0anupBfTQxUfWKTtY95ProcaMhY-_1KI',
    appId: '1:752140122484:android:72881f9804801066c3d421',
    messagingSenderId: '752140122484',
    projectId: 'cookmate-4831f',
    storageBucket: 'cookmate-4831f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsNZkqMWvHNM5zJcuV5mjlBtFx0hLtUec',
    appId: '1:752140122484:web:12f0c68c443582d2c3d421',
    messagingSenderId: '752140122484',
    projectId: 'cookmate-4831f',
    authDomain: 'cookmate-4831f.firebaseapp.com',
    storageBucket: 'cookmate-4831f.firebasestorage.app',
    measurementId: 'G-C0CZP42MKP',
  );
}
