// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs0QXr-xe0nQ6anHMmcmr2zWNj-_VCk3A',
    appId: '1:580966042001:web:c5a465c4a2a9d09526b230',
    messagingSenderId: '580966042001',
    projectId: 'genz-4ac33',
    authDomain: 'genz-4ac33.firebaseapp.com',
    storageBucket: 'genz-4ac33.firebasestorage.app',
    measurementId: 'G-WVEQ4K9B9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmCmKZUb4Hnw_eiiIOSCQzbRONCTBEl7c',
    appId: '1:580966042001:android:4f477fd4d908c1c726b230',
    messagingSenderId: '580966042001',
    projectId: 'genz-4ac33',
    storageBucket: 'genz-4ac33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCay4iGEj_WgAolrYapWFv6ZSCiYrrtmKA',
    appId: '1:580966042001:ios:e447df73bc7e902426b230',
    messagingSenderId: '580966042001',
    projectId: 'genz-4ac33',
    storageBucket: 'genz-4ac33.firebasestorage.app',
    iosBundleId: 'com.example.examMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCay4iGEj_WgAolrYapWFv6ZSCiYrrtmKA',
    appId: '1:580966042001:ios:e447df73bc7e902426b230',
    messagingSenderId: '580966042001',
    projectId: 'genz-4ac33',
    storageBucket: 'genz-4ac33.firebasestorage.app',
    iosBundleId: 'com.example.examMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs0QXr-xe0nQ6anHMmcmr2zWNj-_VCk3A',
    appId: '1:580966042001:web:80e0885627b7d2df26b230',
    messagingSenderId: '580966042001',
    projectId: 'genz-4ac33',
    authDomain: 'genz-4ac33.firebaseapp.com',
    storageBucket: 'genz-4ac33.firebasestorage.app',
    measurementId: 'G-ZXD9DYVZE8',
  );
}
