// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDivrVUgRp4zRLxM5gFDmnunVf4zvvPPyM',
    appId: '1:661593904369:web:1b00db0eebefa6780a0550',
    messagingSenderId: '661593904369',
    projectId: 'my-berwastore-app',
    authDomain: 'my-berwastore-app.firebaseapp.com',
    storageBucket: 'my-berwastore-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKp6xPyhBpmw9NrOfd8-YWeoSx1yTCT0Y',
    appId: '1:661593904369:android:f8105720ee55ade20a0550',
    messagingSenderId: '661593904369',
    projectId: 'my-berwastore-app',
    storageBucket: 'my-berwastore-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAceAgyMrsisWbICZJ_C7BJUOp6qFykgxE',
    appId: '1:661593904369:ios:9f55e18d9bac2bfb0a0550',
    messagingSenderId: '661593904369',
    projectId: 'my-berwastore-app',
    storageBucket: 'my-berwastore-app.firebasestorage.app',
    iosBundleId: 'com.example.berwastore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAceAgyMrsisWbICZJ_C7BJUOp6qFykgxE',
    appId: '1:661593904369:ios:9f55e18d9bac2bfb0a0550',
    messagingSenderId: '661593904369',
    projectId: 'my-berwastore-app',
    storageBucket: 'my-berwastore-app.firebasestorage.app',
    iosBundleId: 'com.example.berwastore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDivrVUgRp4zRLxM5gFDmnunVf4zvvPPyM',
    appId: '1:661593904369:web:fd176ca2b30d05330a0550',
    messagingSenderId: '661593904369',
    projectId: 'my-berwastore-app',
    authDomain: 'my-berwastore-app.firebaseapp.com',
    storageBucket: 'my-berwastore-app.firebasestorage.app',
  );

}