// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53b5QW_BNgl-bWTJTp2S0wFOeQa88L0I',
    appId: '1:409341349119:web:47c5c898b82cab4770d0ca',
    messagingSenderId: '409341349119',
    projectId: 'flutter-75db0',
    authDomain: 'flutter-75db0.firebaseapp.com',
    storageBucket: 'flutter-75db0.firebasestorage.app',
    measurementId: 'G-SY3VH69X0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjc9Ad4tv4WTQw6lOp4lLeYixM2p_Vmo',
    appId: '1:409341349119:android:23f276fec74a1cbf70d0ca',
    messagingSenderId: '409341349119',
    projectId: 'flutter-75db0',
    storageBucket: 'flutter-75db0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyuOOu_oIdRFIsOkzGPHKOLvEv8FG_97g',
    appId: '1:409341349119:ios:419ffbdb51921c4b70d0ca',
    messagingSenderId: '409341349119',
    projectId: 'flutter-75db0',
    storageBucket: 'flutter-75db0.firebasestorage.app',
    iosClientId: '409341349119-t1g4cgo1ajlnb318nj5ca648vudibe19.apps.googleusercontent.com',
    iosBundleId: 'com.example.22rp017882',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyuOOu_oIdRFIsOkzGPHKOLvEv8FG_97g',
    appId: '1:409341349119:ios:419ffbdb51921c4b70d0ca',
    messagingSenderId: '409341349119',
    projectId: 'flutter-75db0',
    storageBucket: 'flutter-75db0.firebasestorage.app',
    iosClientId: '409341349119-t1g4cgo1ajlnb318nj5ca648vudibe19.apps.googleusercontent.com',
    iosBundleId: 'com.example.22rp017882',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB53b5QW_BNgl-bWTJTp2S0wFOeQa88L0I',
    appId: '1:409341349119:web:6fa1973bda1b4a6670d0ca',
    messagingSenderId: '409341349119',
    projectId: 'flutter-75db0',
    authDomain: 'flutter-75db0.firebaseapp.com',
    storageBucket: 'flutter-75db0.firebasestorage.app',
    measurementId: 'G-94TRP4KGXQ',
  );
}
