// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8IapnPHIOUi_YgcY5oO9p2whIu6mkNq0',
    appId: '1:423960351973:web:29d0e2fef753f2823b700c',
    messagingSenderId: '423960351973',
    projectId: 'skillswap-8cdb3',
    authDomain: 'skillswap-8cdb3.firebaseapp.com',
    storageBucket: 'skillswap-8cdb3.firebasestorage.app',
    measurementId: 'G-NYZFSFDTPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkMzR8s5P30dXPhpK0lOmiQNWooAc2XCE',
    appId: '1:423960351973:android:b17fa6b83a39a0553b700c',
    messagingSenderId: '423960351973',
    projectId: 'skillswap-8cdb3',
    storageBucket: 'skillswap-8cdb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO0bUuDRBgW0F6BaLEoHlZ7-4QQoeyhR8',
    appId: '1:423960351973:ios:c3b38034dcd2ac363b700c',
    messagingSenderId: '423960351973',
    projectId: 'skillswap-8cdb3',
    storageBucket: 'skillswap-8cdb3.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO0bUuDRBgW0F6BaLEoHlZ7-4QQoeyhR8',
    appId: '1:423960351973:ios:c3b38034dcd2ac363b700c',
    messagingSenderId: '423960351973',
    projectId: 'skillswap-8cdb3',
    storageBucket: 'skillswap-8cdb3.firebasestorage.app',
    iosBundleId: 'com.example.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8IapnPHIOUi_YgcY5oO9p2whIu6mkNq0',
    appId: '1:423960351973:web:9c11d450f82d17943b700c',
    messagingSenderId: '423960351973',
    projectId: 'skillswap-8cdb3',
    authDomain: 'skillswap-8cdb3.firebaseapp.com',
    storageBucket: 'skillswap-8cdb3.firebasestorage.app',
    measurementId: 'G-SDKLMS7C0Z',
  );
}
