// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQwRF4ryOQw9ebNPFgzQJGyAGOZoecZ0',
    appId: '1:3722144922:web:4d0ad8a32d2dca58784323',
    messagingSenderId: '3722144922',
    projectId: 'eticket-d4568',
    authDomain: 'eticket-d4568.firebaseapp.com',
    storageBucket: 'eticket-d4568.firebasestorage.app',
    measurementId: 'G-0Y2WFR9XXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZxAVh72nEoEOYJZZc6Z-x4TYfBFoYsY',
    appId: '1:3722144922:android:4c5e4dca78cc83d1784323',
    messagingSenderId: '3722144922',
    projectId: 'eticket-d4568',
    storageBucket: 'eticket-d4568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuLsbKBPgGIo4cekNaT6u_Nk3Jg9cuM4Q',
    appId: '1:3722144922:ios:c38403c7102c7ad1784323',
    messagingSenderId: '3722144922',
    projectId: 'eticket-d4568',
    storageBucket: 'eticket-d4568.firebasestorage.app',
    androidClientId: '3722144922-l7g3henmtgfnht9rs0865qspajcjurbq.apps.googleusercontent.com',
    iosClientId: '3722144922-tii19cng9s2a1l78rvtf1915r2gitruu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eticket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuLsbKBPgGIo4cekNaT6u_Nk3Jg9cuM4Q',
    appId: '1:3722144922:ios:c38403c7102c7ad1784323',
    messagingSenderId: '3722144922',
    projectId: 'eticket-d4568',
    storageBucket: 'eticket-d4568.firebasestorage.app',
    androidClientId: '3722144922-l7g3henmtgfnht9rs0865qspajcjurbq.apps.googleusercontent.com',
    iosClientId: '3722144922-tii19cng9s2a1l78rvtf1915r2gitruu.apps.googleusercontent.com',
    iosBundleId: 'com.example.eticket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGQwRF4ryOQw9ebNPFgzQJGyAGOZoecZ0',
    appId: '1:3722144922:web:bbe7c59ba73f4a04784323',
    messagingSenderId: '3722144922',
    projectId: 'eticket-d4568',
    authDomain: 'eticket-d4568.firebaseapp.com',
    storageBucket: 'eticket-d4568.firebasestorage.app',
    measurementId: 'G-9H4W1MQPL5',
  );

}