// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmWmKfi5ZhCWRSeFdladOEJbRtFCeV79k',
    appId: '1:830763958175:web:f69857b37ecea49b1407aa',
    messagingSenderId: '830763958175',
    projectId: 'exam-project-5263f',
    authDomain: 'exam-project-5263f.firebaseapp.com',
    storageBucket: 'exam-project-5263f.appspot.com', // <-- Must end with .appspot.com
    measurementId: 'G-X4TBSFNRHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDDdIxXMVvFEhRWL1BQHIK_OcjcWP3CE',
    appId: '1:830763958175:android:3bbe2df1f55bd6221407aa',
    messagingSenderId: '830763958175',
    projectId: 'exam-project-5263f',
    storageBucket: 'exam-project-5263f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8GDYFi_Ayyk1YkK5F-BqwXqedZoSm_xA',
    appId: '1:830763958175:ios:3845c5e60dfb9ac21407aa',
    messagingSenderId: '830763958175',
    projectId: 'exam-project-5263f',
    storageBucket: 'exam-project-5263f.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8GDYFi_Ayyk1YkK5F-BqwXqedZoSm_xA',
    appId: '1:830763958175:ios:3845c5e60dfb9ac21407aa',
    messagingSenderId: '830763958175',
    projectId: 'exam-project-5263f',
    storageBucket: 'exam-project-5263f.firebasestorage.app',
    iosBundleId: 'com.example.mobileAppExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmWmKfi5ZhCWRSeFdladOEJbRtFCeV79k',
    appId: '1:830763958175:web:27186000ab636b501407aa',
    messagingSenderId: '830763958175',
    projectId: 'exam-project-5263f',
    authDomain: 'exam-project-5263f.firebaseapp.com',
    storageBucket: 'exam-project-5263f.firebasestorage.app',
    measurementId: 'G-CJRFRYPJ6X',
  );
}
