// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlH--F_4tkKV4L90f-JjRxX00VyuB-P9E',
    appId: '1:699410683691:web:16c464cad4b2607f96d76e',
    messagingSenderId: '699410683691',
    projectId: 'medical-app-db',
    authDomain: 'medical-app-db.firebaseapp.com',
    storageBucket: 'medical-app-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_09a2OE-oq35OSLjgo2wibGLSe4HB6Q',
    appId: '1:699410683691:android:73d7465225160a4096d76e',
    messagingSenderId: '699410683691',
    projectId: 'medical-app-db',
    storageBucket: 'medical-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD02k_KkToun-jxSaC0Y_sqgzMCB-O_ryk',
    appId: '1:699410683691:ios:d12f4da47c06278d96d76e',
    messagingSenderId: '699410683691',
    projectId: 'medical-app-db',
    storageBucket: 'medical-app-db.firebasestorage.app',
    iosBundleId: 'com.example.medicalreminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD02k_KkToun-jxSaC0Y_sqgzMCB-O_ryk',
    appId: '1:699410683691:ios:d12f4da47c06278d96d76e',
    messagingSenderId: '699410683691',
    projectId: 'medical-app-db',
    storageBucket: 'medical-app-db.firebasestorage.app',
    iosBundleId: 'com.example.medicalreminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlH--F_4tkKV4L90f-JjRxX00VyuB-P9E',
    appId: '1:699410683691:web:592c8cdccd1122b396d76e',
    messagingSenderId: '699410683691',
    projectId: 'medical-app-db',
    authDomain: 'medical-app-db.firebaseapp.com',
    storageBucket: 'medical-app-db.firebasestorage.app',
  );
}
