// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW44VVMdRbRxGxSkCmnAIoYNalVditABs',
    appId: '1:260532571296:web:20deaf919917e40b0f8dc5',
    messagingSenderId: '260532571296',
    projectId: 'neighborhoodalert',
    authDomain: 'neighborhoodalert.firebaseapp.com',
    storageBucket: 'neighborhoodalert.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9CWHzNJJIZxz7C7NuH7zjCdzIfcw8WI',
    appId: '1:260532571296:android:227e466ce015ebc50f8dc5',
    messagingSenderId: '260532571296',
    projectId: 'neighborhoodalert',
    storageBucket: 'neighborhoodalert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD5ZU5455jwP_9uOjD-BKobYAlOijzpn8',
    appId: '1:260532571296:ios:61677cdbd46c56a40f8dc5',
    messagingSenderId: '260532571296',
    projectId: 'neighborhoodalert',
    storageBucket: 'neighborhoodalert.firebasestorage.app',
    iosBundleId: 'com.example.neihborhoodalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD5ZU5455jwP_9uOjD-BKobYAlOijzpn8',
    appId: '1:260532571296:ios:61677cdbd46c56a40f8dc5',
    messagingSenderId: '260532571296',
    projectId: 'neighborhoodalert',
    storageBucket: 'neighborhoodalert.firebasestorage.app',
    iosBundleId: 'com.example.neihborhoodalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW44VVMdRbRxGxSkCmnAIoYNalVditABs',
    appId: '1:260532571296:web:1611a042648801040f8dc5',
    messagingSenderId: '260532571296',
    projectId: 'neighborhoodalert',
    authDomain: 'neighborhoodalert.firebaseapp.com',
    storageBucket: 'neighborhoodalert.firebasestorage.app',
  );
}
