// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
apiKey: "AIzaSyCV5nf4gJkBB2qkeEUUcRZAyqHhCPyFMXw",
  authDomain: "kazi-link-b9ae8.firebaseapp.com",
  projectId: "kazi-link-b9ae8",
  storageBucket: "kazi-link-b9ae8.firebasestorage.app",
  messagingSenderId: "453251953352",
  appId: "1:453251953352:web:9c9946e768ffae13466bfd",
  measurementId: "G-98DWT4JR51"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAayljcbkRVSDnpH-NxvmPIo4JuBEb6RYo',
    appId: '1:453251953352:android:aacf03e44d4eebad466bfd',
    messagingSenderId: '453251953352',
    projectId: 'kazi-link-b9ae8',
    storageBucket: 'kazi-link-b9ae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADfpbmkk8EEIY5uB3SO12Ty9y1FyXPz2Y',
    appId: '1:453251953352:ios:f6e21af4d8cb6c32466bfd',
    messagingSenderId: '453251953352',
    projectId: 'kazi-link-b9ae8',
    storageBucket: 'kazi-link-b9ae8.firebasestorage.app',
    iosBundleId: 'com.example.kaziLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADfpbmkk8EEIY5uB3SO12Ty9y1FyXPz2Y',
    appId: '1:453251953352:ios:f6e21af4d8cb6c32466bfd',
    messagingSenderId: '453251953352',
    projectId: 'kazi-link-b9ae8',
    storageBucket: 'kazi-link-b9ae8.firebasestorage.app',
    iosBundleId: 'com.example.kaziLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
   apiKey: "AIzaSyCV5nf4gJkBB2qkeEUUcRZAyqHhCPyFMXw",
  authDomain: "kazi-link-b9ae8.firebaseapp.com",
  projectId: "kazi-link-b9ae8",
  storageBucket: "kazi-link-b9ae8.firebasestorage.app",
  messagingSenderId: "453251953352",
  appId: "1:453251953352:web:9c9946e768ffae13466bfd",
  measurementId: "G-98DWT4JR51"
  );
}
