// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnXFXG_pN1W8RQ9J1TU6Hk2l1CRZp1_fA',
    appId: '1:434593846654:web:5f0e4d925bcf50e19c0f2f',
    messagingSenderId: '434593846654',
    projectId: 'ceremo-car-app',
    authDomain: 'ceremo-car-app.firebaseapp.com',
    storageBucket: 'ceremo-car-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPZXbKOCM-q0PfbNFhvNHaXqfIVMdpI6g',
    appId: '1:434593846654:android:d6b2e42f7b7f5dbf9c0f2f',
    messagingSenderId: '434593846654',
    projectId: 'ceremo-car-app',
    storageBucket: 'ceremo-car-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTk4CAyTw0bh-qoEC3o5fGxnaoHMMykA',
    appId: '1:434593846654:ios:7f438f56ebf6d3009c0f2f',
    messagingSenderId: '434593846654',
    projectId: 'ceremo-car-app',
    storageBucket: 'ceremo-car-app.firebasestorage.app',
    iosBundleId: 'com.example.ceremocar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTk4CAyTw0bh-qoEC3o5fGxnaoHMMykA',
    appId: '1:434593846654:ios:7f438f56ebf6d3009c0f2f',
    messagingSenderId: '434593846654',
    projectId: 'ceremo-car-app',
    storageBucket: 'ceremo-car-app.firebasestorage.app',
    iosBundleId: 'com.example.ceremocar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnXFXG_pN1W8RQ9J1TU6Hk2l1CRZp1_fA',
    appId: '1:434593846654:web:944f41fdb4fcf48c9c0f2f',
    messagingSenderId: '434593846654',
    projectId: 'ceremo-car-app',
    authDomain: 'ceremo-car-app.firebaseapp.com',
    storageBucket: 'ceremo-car-app.firebasestorage.app',
  );
}
